local addon = select(2, ...)

-- Each addon's launcher icon as its own source sets it; relative paths sit in its folder, tables add texcoords.
addon.AddonManagerKnownIcons = {
    ["adibags"] = "Interface\\Buttons\\Button-Backpack-Up",
    ["atlas"] = "Interface\\WorldMap\\WorldMap-Icon",
    ["atlasloot"] = "Interface\\Icons\\INV_Box_01",
    ["bagnon"] = "Interface\\Icons\\INV_Misc_Bag_07",
    ["bankitems"] = "Interface\\Icons\\INV_Misc_Bag_10_Blue",
    ["bankstack"] = "Interface\\Icons\\INV_Misc_Shovel_01",
    ["bartender4"] = "Interface\\Icons\\INV_Drink_05",
    ["bigwigs"] = "Textures\\icons\\core-enabled",
    ["bistooltip"] = "Interface\\Icons\\INV_Weapon_Glave_01",
    ["carbonite"] = "Gfx\\MMBut",
    ["dbm-core"] = { { "textures\\dbm_airhorn" }, { "textures\\Minimap-Button-Up" } },
    ["decursive"] = "iconON",
    ["details"] = "images\\minimap",
    ["drdamage"] = "Interface\\Icons\\Spell_Holy_SearingLightPriest",
    ["gatherer"] = { "Skin\\GatherOrb", 0.075, 0.925, 0.075, 0.925 },
    ["gathermate2"] = "Artwork\\Icon",
    ["gearscore"] = "Interface\\Icons\\INV_Chest_Plate12",
    ["grid2"] = "media\\icon",
    ["healbot"] = "Images\\HealBot",
    ["icehud"] = "Interface\\Icons\\Spell_Frost_Frost",
    ["leatrix_plus"] = "assets\\reportlagicon-movement",
    ["minimapbuttonframe"] = "Interface\\Icons\\INV_Misc_Coin_11",
    ["notplater"] = "images\\logo",
    ["omen"] = "icon",
    ["ora2"] = "Icons\\core_enabled",
    ["pawn"] = { "Textures\\PawnLogo", 0, 0.5, 0, 1 },
    ["pfquest"] = { "img\\logo", 0.05, 0.95, 0.05, 0.95 },
    ["pitbull4"] = "pitbull",
    ["prat-3.0"] = "textures\\chat-bubble",
    ["questhelper"] = "Interface\\QuestFrame\\UI-QuestLog-BookIcon",
    ["questie"] = "Icons\\complete",
    ["questie-ashenorder"] = "Icons\\complete",
    ["raidbuffstatus"] = "Interface\\Icons\\Ability_Hunter_MasterMarksman",
    ["raidroll"] = "Interface\\Icons\\INV_Helmet_74",
    ["scrap"] = "Textures\\Enabled Icon",
    ["silverdragon"] = "Interface\\Icons\\INV_Misc_Head_Dragon_01",
    ["skada"] = "Interface\\Icons\\Spell_Lightning_LightningBolt01",
    ["tidyplates"] = "media\\TidyPlatesIcon",
    ["tomtom"] = "Interface\\Icons\\INV_Misc_Map_01",
    ["tourguide"] = "Interface\\Icons\\Ability_Rogue_Sprint",
    ["tradeskillinfo"] = "Interface\\Icons\\INV_Elemental_Mote_Nether",
    ["tradeskillmaster"] = "Media\\TSM_Icon",
    ["vuhdo"] = "Images\\VuhDo",
    ["weakauras"] = "Media\\Textures\\icon",
    ["xperl"] = "Interface\\Icons\\INV_Misc_Gem_Pearl_02",
    ["zygorguidesviewer"] = {
        { "Skin\\violet\\zglogo", 0, 1, 0, 0.25 },
        { "Skin\\modern\\zglogo", 0, 1, 0, 0.25 },
        { "Skin\\remaster\\zglogo", 0, 1, 0, 0.25 },
    },
    ["zygorguidesviewerrm"] = {
        { "Skin\\remaster\\zglogo", 0, 1, 0, 0.25 },
        { "Skin\\violet\\zglogo", 0, 1, 0, 0.25 },
    },
}
