-- Copyright (c) 2026 NeticSoul. Licensed under the MIT License; see LICENSE.

-- GENERATED from TaxiNodes.dbc and WorldMapArea.dbc. Do not edit.

local addon = select(2, ...)

addon.WorldMap.FlightPoints = {
  ["Arathi"] = {
    { x = 0.4579, y = 0.4613, name = "Refuge Pointe, Arathi", faction = "Alliance" },
    { x = 0.7306, y = 0.3262, name = "Hammerfall, Arathi", faction = "Horde" },
  },
  ["Ashenvale"] = {
    { x = 0.1219, y = 0.3377, name = "Zoram'gar Outpost, Ashenvale", faction = "Horde" },
    { x = 0.3450, y = 0.4801, name = "Astranaar, Ashenvale", faction = "Alliance" },
    { x = 0.7326, y = 0.6167, name = "Splintertree Post, Ashenvale", faction = "Horde" },
    { x = 0.8501, y = 0.4352, name = "Forest Song, Ashenvale", faction = "Alliance" },
  },
  ["Aszhara"] = {
    { x = 0.1190, y = 0.7748, name = "Talrendis Point, Azshara", faction = "Alliance" },
    { x = 0.2195, y = 0.4969, name = "Valormok, Azshara", faction = "Horde" },
  },
  ["AzuremystIsle"] = {
    { x = 0.3177, y = 0.4646, name = "The Exodar", faction = "Alliance" },
  },
  ["Badlands"] = {
    { x = 0.0406, y = 0.4489, name = "Kargath, Badlands", faction = "Horde" },
  },
  ["Barrens"] = {
    { x = 0.4446, y = 0.5910, name = "Camp Taurajo, The Barrens", faction = "Horde" },
    { x = 0.5150, y = 0.3041, name = "Crossroads, The Barrens", faction = "Horde" },
    { x = 0.6312, y = 0.3711, name = "Ratchet, The Barrens" },
  },
  ["BladesEdgeMountains"] = {
    { x = 0.2809, y = 0.5191, name = "Ogri'La" },
    { x = 0.3781, y = 0.6151, name = "Sylvanaar, Blade's Edge Mountains", faction = "Alliance" },
    { x = 0.5207, y = 0.5425, name = "Thunderlord Stronghold, Blade's Edge Mountains", faction = "Horde" },
    { x = 0.6109, y = 0.7053, name = "Toshley's Station, Blade's Edge Mountains", faction = "Alliance" },
    { x = 0.6165, y = 0.3960, name = "Evergrove, Blade's Edge Mountains" },
    { x = 0.7632, y = 0.6579, name = "Mok'Nathal Village, Blade's Edge Mountains", faction = "Horde" },
  },
  ["BlastedLands"] = {
    { x = 0.6549, y = 0.2443, name = "Nethergarde Keep, Blasted Lands", faction = "Alliance" },
  },
  ["BloodmystIsle"] = {
    { x = 0.5761, y = 0.5402, name = "Blood Watch, Bloodmyst Isle", faction = "Alliance" },
  },
  ["BoreanTundra"] = {
    { x = 0.3312, y = 0.3441, name = "Transitus Shield, Coldarra" },
    { x = 0.4038, y = 0.5145, name = "Warsong Hold, Borean Tundra", faction = "Horde" },
    { x = 0.4506, y = 0.3408, name = "Amber Ledge, Borean Tundra" },
    { x = 0.4959, y = 0.1101, name = "Bor'gorok Outpost, Borean Tundra", faction = "Horde" },
    { x = 0.5651, y = 0.2005, name = "Fizzcrank Airstrip, Borean Tundra", faction = "Alliance" },
    { x = 0.5893, y = 0.6838, name = "Valiance Keep, Borean Tundra", faction = "Alliance" },
    { x = 0.7774, y = 0.3768, name = "Taunka'le Village, Borean Tundra", faction = "Horde" },
    { x = 0.7849, y = 0.5148, name = "Unu'pe, Borean Tundra" },
  },
  ["BurningSteppes"] = {
    { x = 0.6558, y = 0.2422, name = "Flame Crest, Burning Steppes", faction = "Horde" },
    { x = 0.8438, y = 0.6830, name = "Morgan's Vigil, Burning Steppes", faction = "Alliance" },
  },
  ["CrystalsongForest"] = {
    { x = 0.3653, y = 0.3793, name = "Dalaran" },
    { x = 0.7212, y = 0.8081, name = "Windrunner's Overlook, Crystalsong Forest", faction = "Alliance" },
    { x = 0.7848, y = 0.5024, name = "Sunreaver's Command, Crystalsong Forest", faction = "Horde" },
  },
  ["Darkshore"] = {
    { x = 0.3640, y = 0.4562, name = "Auberdine, Darkshore", faction = "Alliance" },
  },
  ["Desolace"] = {
    { x = 0.2156, y = 0.7404, name = "Shadowprey Village, Desolace", faction = "Horde" },
    { x = 0.6467, y = 0.1044, name = "Nijel's Point, Desolace", faction = "Alliance" },
  },
  ["Dragonblight"] = {
    { x = 0.2915, y = 0.5538, name = "Stars' Rest, Dragonblight", faction = "Alliance" },
    { x = 0.3747, y = 0.4570, name = "Agmar's Hammer, Dragonblight", faction = "Horde" },
    { x = 0.3959, y = 0.2575, name = "Fordragon Hold, Dragonblight", faction = "Alliance" },
    { x = 0.4388, y = 0.1680, name = "Kor'koron Vanguard, Dragonblight", faction = "Horde" },
    { x = 0.4847, y = 0.7441, name = "Moa'ki, Dragonblight" },
    { x = 0.6026, y = 0.5139, name = "Wyrmrest Temple, Dragonblight" },
    { x = 0.7655, y = 0.6236, name = "Venomspite, Dragonblight", faction = "Horde" },
    { x = 0.7706, y = 0.4981, name = "Wintergarde Keep, Dragonblight", faction = "Alliance" },
  },
  ["DunMorogh"] = {
    { x = 0.6005, y = 0.2877, name = "Ironforge, Dun Morogh", faction = "Alliance" },
  },
  ["Durotar"] = {
    { x = 0.4451, y = 0.0371, name = "Orgrimmar, Durotar", faction = "Horde" },
  },
  ["Duskwood"] = {
    { x = 0.7759, y = 0.4438, name = "Darkshire, Duskwood", faction = "Alliance" },
  },
  ["Dustwallow"] = {
    { x = 0.3557, y = 0.3183, name = "Brackenwall Village, Dustwallow Marsh", faction = "Horde" },
    { x = 0.4288, y = 0.7237, name = "Mudsprocket, Dustwallow Marsh" },
    { x = 0.6746, y = 0.5120, name = "Theramore, Dustwallow Marsh", faction = "Alliance" },
  },
  ["EasternPlaguelands"] = {
    { x = 0.1892, y = 0.2625, name = "Plaguewood Tower, Eastern Plaguelands" },
    { x = 0.3401, y = 0.6871, name = "Crown Guard Tower, Eastern Plaguelands" },
    { x = 0.4955, y = 0.2213, name = "Northpass Tower, Eastern Plaguelands" },
    { x = 0.6091, y = 0.4483, name = "Eastwall Tower, Eastern Plaguelands" },
    { x = 0.7574, y = 0.5332, name = "Light's Hope Chapel, Eastern Plaguelands" },
    { x = 0.8383, y = 0.5030, name = "Acherus: The Ebon Hold" },
  },
  ["Elwynn"] = {
    { x = 0.3013, y = 0.3893, name = "Stormwind, Elwynn", faction = "Alliance" },
  },
  ["EversongWoods"] = {
    { x = 0.5438, y = 0.5075, name = "Silvermoon City", faction = "Horde" },
  },
  ["Felwood"] = {
    { x = 0.3442, y = 0.5387, name = "Bloodvenom Post, Felwood", faction = "Horde" },
    { x = 0.5144, y = 0.8229, name = "Emerald Sanctuary, Felwood" },
    { x = 0.6246, y = 0.2419, name = "Talonbranch Glade, Felwood", faction = "Alliance" },
  },
  ["Feralas"] = {
    { x = 0.3026, y = 0.4332, name = "Feathermoon, Feralas", faction = "Alliance" },
    { x = 0.7543, y = 0.4431, name = "Camp Mojache, Feralas", faction = "Horde" },
    { x = 0.8946, y = 0.4587, name = "Thalanaar, Feralas", faction = "Alliance" },
  },
  ["Ghostlands"] = {
    { x = 0.4548, y = 0.3055, name = "Tranquillien, Ghostlands", faction = "Horde" },
    { x = 0.7467, y = 0.6713, name = "Zul'Aman, Ghostlands" },
  },
  ["GrizzlyHills"] = {
    { x = 0.3131, y = 0.5915, name = "Amberpine Lodge, Grizzly Hills", faction = "Alliance" },
    { x = 0.5989, y = 0.2662, name = "Westfall Brigade, Grizzly Hills", faction = "Alliance" },
    { x = 0.6495, y = 0.4687, name = "Camp Oneqwah, Grizzly Hills", faction = "Horde" },
  },
  ["Hellfire"] = {
    { x = 0.2513, y = 0.3723, name = "Temple of Telhamat, Hellfire Peninsula", faction = "Alliance" },
    { x = 0.2785, y = 0.6007, name = "Falcon Watch, Hellfire Peninsula", faction = "Horde" },
    { x = 0.5465, y = 0.6257, name = "Honor Hold, Hellfire Peninsula", faction = "Alliance" },
    { x = 0.5627, y = 0.3638, name = "Thrallmar, Hellfire Peninsula", faction = "Horde" },
    { x = 0.6159, y = 0.8125, name = "Spinebreaker Ridge, Hellfire Peninsula", faction = "Horde" },
    { x = 0.7847, y = 0.3499, name = "Shatter Point, Hellfire Peninsula", faction = "Alliance" },
    { x = 0.8738, y = 0.4818, name = "Hellfire Peninsula, The Dark Portal, Horde", faction = "Horde" },
    { x = 0.8750, y = 0.5252, name = "Hellfire Peninsula, The Dark Portal, Alliance", faction = "Alliance" },
  },
  ["Hilsbrad"] = {
    { x = 0.4944, y = 0.5210, name = "Southshore, Hillsbrad", faction = "Alliance" },
    { x = 0.6021, y = 0.1875, name = "Tarren Mill, Hillsbrad", faction = "Horde" },
  },
  ["Hinterlands"] = {
    { x = 0.1111, y = 0.4609, name = "Aerie Peak, The Hinterlands", faction = "Alliance" },
    { x = 0.8170, y = 0.8189, name = "Revantusk Village, The Hinterlands", faction = "Horde" },
  },
  ["HowlingFjord"] = {
    { x = 0.2464, y = 0.5783, name = "Kamagua, Howling Fjord" },
    { x = 0.2601, y = 0.2502, name = "Apothecary Camp, Howling Fjord", faction = "Horde" },
    { x = 0.3126, y = 0.4400, name = "Westguard Keep, Howling Fjord", faction = "Alliance" },
    { x = 0.4953, y = 0.1150, name = "Camp Winterhoof, Howling Fjord", faction = "Horde" },
    { x = 0.5204, y = 0.6736, name = "New Agamand, Howling Fjord", faction = "Horde" },
    { x = 0.5976, y = 0.6324, name = "Valgarde Port, Howling Fjord", faction = "Alliance" },
    { x = 0.6007, y = 0.1607, name = "Fort Wildervar, Howling Fjord", faction = "Alliance" },
    { x = 0.7903, y = 0.2972, name = "Vengeance Landing, Howling Fjord", faction = "Horde" },
  },
  ["IcecrownGlacier"] = {
    { x = 0.1945, y = 0.4783, name = "Death's Rise, Icecrown" },
    { x = 0.4371, y = 0.2437, name = "The Shadow Vault, Icecrown" },
    { x = 0.7260, y = 0.2275, name = "Argent Tournament Grounds, Icecrown" },
    { x = 0.7935, y = 0.7235, name = "Crusaders' Pinnacle, Icecrown" },
    { x = 0.8779, y = 0.7803, name = "The Argent Vanguard, Icecrown" },
  },
  ["Ironforge"] = {
    { x = 0.5589, y = 0.4787, name = "Ironforge, Dun Morogh", faction = "Alliance" },
  },
  ["LakeWintergrasp"] = {
    { x = 0.2163, y = 0.3487, name = "Warsong Camp, Wintergrasp", faction = "Horde" },
    { x = 0.7205, y = 0.3105, name = "Valiance Landing Camp, Wintergrasp", faction = "Alliance" },
  },
  ["LochModan"] = {
    { x = 0.3394, y = 0.5079, name = "Thelsamar, Loch Modan", faction = "Alliance" },
  },
  ["Moonglade"] = {
    { x = 0.3215, y = 0.6633, name = "Moonglade", faction = "Horde" },
    { x = 0.4428, y = 0.4534, name = "Nighthaven, Moonglade" },
    { x = 0.4791, y = 0.6711, name = "Moonglade", faction = "Alliance" },
  },
  ["Mulgore"] = {
    { x = 0.3928, y = 0.2699, name = "Thunder Bluff, Mulgore", faction = "Horde" },
  },
  ["Nagrand"] = {
    { x = 0.5413, y = 0.7522, name = "Telaar, Nagrand", faction = "Alliance" },
    { x = 0.5724, y = 0.3537, name = "Garadar, Nagrand", faction = "Horde" },
  },
  ["Netherstorm"] = {
    { x = 0.3385, y = 0.6387, name = "Area 52, Netherstorm" },
    { x = 0.4527, y = 0.3494, name = "The Stormspire, Netherstorm" },
    { x = 0.6520, y = 0.6676, name = "Cosmowrench, Netherstorm" },
  },
  ["Ogrimmar"] = {
    { x = 0.4528, y = 0.6375, name = "Orgrimmar, Durotar", faction = "Horde" },
  },
  ["Redridge"] = {
    { x = 0.3043, y = 0.5899, name = "Lakeshire, Redridge", faction = "Alliance" },
  },
  ["SearingGorge"] = {
    { x = 0.3483, y = 0.3058, name = "Thorium Point, Searing Gorge", faction = "Horde" },
    { x = 0.3789, y = 0.3043, name = "Thorium Point, Searing Gorge", faction = "Alliance" },
  },
  ["ShadowmoonValley"] = {
    { x = 0.3033, y = 0.2920, name = "Shadowmoon Village, Shadowmoon Valley", faction = "Horde" },
    { x = 0.3761, y = 0.5548, name = "Wildhammer Stronghold, Shadowmoon Valley", faction = "Alliance" },
    { x = 0.5639, y = 0.5796, name = "Sanctum of the Stars, Shadowmoon Valley" },
    { x = 0.6319, y = 0.3048, name = "Altar of Sha'tar, Shadowmoon Valley" },
  },
  ["ShattrathCity"] = {
    { x = 0.6380, y = 0.4172, name = "Shattrath, Terokkar Forest" },
  },
  ["SholazarBasin"] = {
    { x = 0.2536, y = 0.5824, name = "Nesingwary Base Camp, Sholazar Basin" },
    { x = 0.5007, y = 0.6133, name = "River's Heart, Sholazar Basin" },
  },
  ["Silithus"] = {
    { x = 0.4883, y = 0.3672, name = "Cenarion Hold, Silithus" },
  },
  ["SilvermoonCity"] = {
    { x = 0.6316, y = 0.9649, name = "Silvermoon City", faction = "Horde" },
  },
  ["Silverpine"] = {
    { x = 0.4556, y = 0.4242, name = "The Sepulcher, Silverpine Forest", faction = "Horde" },
  },
  ["StonetalonMountains"] = {
    { x = 0.3654, y = 0.0723, name = "Stonetalon Peak, Stonetalon Mountains", faction = "Alliance" },
    { x = 0.4516, y = 0.5989, name = "Sun Rock Retreat, Stonetalon Mountains", faction = "Horde" },
  },
  ["Stormwind"] = {
    { x = 0.7098, y = 0.7293, name = "Stormwind, Elwynn", faction = "Alliance" },
  },
  ["Stranglethorn"] = {
    { x = 0.2682, y = 0.7700, name = "Booty Bay, Stranglethorn" },
    { x = 0.3010, y = 0.7294, name = "Booty Bay, Stranglethorn", faction = "Alliance" },
    { x = 0.3251, y = 0.2928, name = "Grom'gol, Stranglethorn", faction = "Horde" },
    { x = 0.3820, y = 0.0412, name = "Rebel Camp, Stranglethorn Vale", faction = "Alliance" },
  },
  ["Sunwell"] = {
    { x = 0.4828, y = 0.2506, name = "Shattered Sun Staging Area" },
  },
  ["SwampOfSorrows"] = {
    { x = 0.4605, y = 0.5468, name = "Stonard, Swamp of Sorrows", faction = "Horde" },
  },
  ["Tanaris"] = {
    { x = 0.5095, y = 0.2933, name = "Gadgetzan, Tanaris", faction = "Alliance" },
    { x = 0.5162, y = 0.2552, name = "Gadgetzan, Tanaris", faction = "Horde" },
  },
  ["Teldrassil"] = {
    { x = 0.5545, y = 0.9222, name = "Fishing Village, Teldrassil", faction = "Alliance" },
    { x = 0.5840, y = 0.9393, name = "Rut'theran Village, Teldrassil", faction = "Alliance" },
  },
  ["TerokkarForest"] = {
    { x = 0.3299, y = 0.2326, name = "Shattrath, Terokkar Forest" },
    { x = 0.4925, y = 0.4354, name = "Stonebreaker Hold, Terokkar Forest", faction = "Horde" },
    { x = 0.5945, y = 0.5520, name = "Allerian Stronghold, Terokkar Forest", faction = "Alliance" },
    { x = 0.6358, y = 0.6569, name = "Skettis" },
  },
  ["TheExodar"] = {
    { x = 0.6879, y = 0.6318, name = "The Exodar", faction = "Alliance" },
  },
  ["TheStormPeaks"] = {
    { x = 0.2953, y = 0.7446, name = "Frosthold, The Storm Peaks", faction = "Alliance" },
    { x = 0.3062, y = 0.3639, name = "Bouldercrag's Refuge, The Storm Peaks" },
    { x = 0.3623, y = 0.4936, name = "Grom'arsh Crash-Site, The Storm Peaks", faction = "Horde" },
    { x = 0.4070, y = 0.8459, name = "K3, The Storm Peaks" },
    { x = 0.4451, y = 0.2812, name = "Ulduar, The Storm Peaks" },
    { x = 0.6256, y = 0.6095, name = "Dun Nifflelem, The Storm Peaks" },
    { x = 0.6540, y = 0.5070, name = "Camp Tunka'lo, The Storm Peaks", faction = "Horde" },
  },
  ["ThousandNeedles"] = {
    { x = 0.4502, y = 0.4913, name = "Freewind Post, Thousand Needles", faction = "Horde" },
  },
  ["ThunderBluff"] = {
    { x = 0.4665, y = 0.4990, name = "Thunder Bluff, Mulgore", faction = "Horde" },
  },
  ["Tirisfal"] = {
    { x = 0.6120, y = 0.7532, name = "Undercity, Tirisfal", faction = "Horde" },
    { x = 0.8352, y = 0.7006, name = "The Bulwark, Tirisfal", faction = "Horde" },
  },
  ["Undercity"] = {
    { x = 0.6309, y = 0.4832, name = "Undercity, Tirisfal", faction = "Horde" },
  },
  ["UngoroCrater"] = {
    { x = 0.4530, y = 0.0597, name = "Marshal's Refuge, Un'Goro Crater" },
  },
  ["WesternPlaguelands"] = {
    { x = 0.4295, y = 0.8495, name = "Chillwind Camp, Western Plaguelands", faction = "Alliance" },
    { x = 0.6921, y = 0.4968, name = "Thondoril River, Western Plaguelands" },
  },
  ["Westfall"] = {
    { x = 0.5656, y = 0.5268, name = "Sentinel Hill, Westfall", faction = "Alliance" },
  },
  ["Wetlands"] = {
    { x = 0.0952, y = 0.5966, name = "Menethil Harbor, Wetlands", faction = "Alliance" },
  },
  ["Winterspring"] = {
    { x = 0.6233, y = 0.3669, name = "Everlook, Winterspring" },
  },
  ["Zangarmarsh"] = {
    { x = 0.3300, y = 0.5119, name = "Zabra'jin, Zangarmarsh", faction = "Horde" },
    { x = 0.4129, y = 0.2890, name = "Orebor Harborage, Zangarmarsh", faction = "Alliance" },
    { x = 0.6786, y = 0.5136, name = "Telredor, Zangarmarsh", faction = "Alliance" },
    { x = 0.8474, y = 0.5500, name = "Swamprat Post, Zangarmarsh", faction = "Horde" },
  },
  ["ZulDrak"] = {
    { x = 0.1406, y = 0.7359, name = "Ebon Watch, Zul'Drak" },
    { x = 0.3217, y = 0.7445, name = "Light's Breach, Zul'Drak" },
    { x = 0.4018, y = 0.6664, name = "Argent Stand, Zul'Drak" },
    { x = 0.5997, y = 0.5681, name = "Zim'Torga, Zul'Drak" },
    { x = 0.7045, y = 0.2316, name = "Gundrak, Zul'Drak" },
  },
}

-- Locale, then the generated name, to what that client's own DBC calls the node.
addon.WorldMap.FlightPointName = {
  ["deDE"] = {
    ["Acherus: The Ebon Hold"] = "Acherus: Die Schwarze Festung",
    ["Aerie Peak, The Hinterlands"] = "Nistgipfel, Hinterland",
    ["Agmar's Hammer, Dragonblight"] = "Agmars Hammer, Drachenöde",
    ["Allerian Stronghold, Terokkar Forest"] = "Allerias Feste, Wälder von Terokkar",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "Altar der Sha'tar, Schattenmondtal",
    ["Amber Ledge, Borean Tundra"] = "Bernsteinflöz, Boreanische Tundra",
    ["Amberpine Lodge, Grizzly Hills"] = "Ammertannhütte, Grizzlyhügel",
    ["Apothecary Camp, Howling Fjord"] = "Apothekerlager, Heulender Fjord",
    ["Area 52, Netherstorm"] = "Area 52, Nethersturm",
    ["Argent Stand, Zul'Drak"] = "Argentumwache, Zul'Drak",
    ["Argent Tournament Grounds, Icecrown"] = "Argentumturnierplatz, Eiskrone",
    ["Astranaar, Ashenvale"] = "Astranaar, Eschental",
    ["Auberdine, Darkshore"] = "Auberdine, Dunkelküste",
    ["Blood Watch, Bloodmyst Isle"] = "Blutwacht, Blutmythosinsel",
    ["Bloodvenom Post, Felwood"] = "Blutgiftposten, Teufelswald",
    ["Booty Bay, Stranglethorn"] = "Beutebucht, Schlingendorntal",
    ["Bor'gorok Outpost, Borean Tundra"] = "Bor'goroks Außenposten, Boreanische Tundra",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "Bergfels' Zuflucht, Sturmgipfel",
    ["Brackenwall Village, Dustwallow Marsh"] = "Brackenwall, Düstermarschen",
    ["Camp Oneqwah, Grizzly Hills"] = "Camp Oneqwah, Grizzlyhügel",
    ["Camp Taurajo, The Barrens"] = "Camp Taurajo, Brachland",
    ["Camp Tunka'lo, The Storm Peaks"] = "Camp Tunka'lo, Die Sturmgipfel",
    ["Camp Winterhoof, Howling Fjord"] = "Lager der Winterhufe, Heulender Fjord",
    ["Cenarion Hold, Silithus"] = "Burg Cenarius, Silithus",
    ["Chillwind Camp, Western Plaguelands"] = "Zugwindlager, Westliche Pestländer",
    ["Cosmowrench, Netherstorm"] = "Kosmozang, Nethersturm",
    ["Crossroads, The Barrens"] = "Das Wegekreuz, Brachland",
    ["Crown Guard Tower, Eastern Plaguelands"] = "Turm der Kronenwache, Östliche Pestländer",
    ["Crusaders' Pinnacle, Icecrown"] = "Kreuzfahrerturm, Eiskrone",
    ["Darkshire, Duskwood"] = "Dunkelhain, Dämmerwald",
    ["Death's Rise, Icecrown"] = "Todesanhöhe, Eiskrone",
    ["Dun Nifflelem, The Storm Peaks"] = "Dun Niffelem, Die Sturmgipfel",
    ["Eastwall Tower, Eastern Plaguelands"] = "Ostwallturm, Östliche Pestländer",
    ["Ebon Watch, Zul'Drak"] = "Schwarze Wacht, Zul'Drak",
    ["Emerald Sanctuary, Felwood"] = "Smaragdrefugium, Teufelswald",
    ["Evergrove, Blade's Edge Mountains"] = "Der ewige Hain, Schergrat",
    ["Everlook, Winterspring"] = "Ewige Warte, Winterquell",
    ["Falcon Watch, Hellfire Peninsula"] = "Falkenwacht, Höllenfeuerhalbinsel",
    ["Feathermoon, Feralas"] = "Mondfederfeste, Feralas",
    ["Fishing Village, Teldrassil"] = "Fischerdorf, Teldrassil",
    ["Fizzcrank Airstrip, Borean Tundra"] = "Landebahn Kurbelzisch, Boreanische Tundra",
    ["Flame Crest, Burning Steppes"] = "Flammenkamm, Brennende Steppe",
    ["Fordragon Hold, Dragonblight"] = "Feste Fordragon, Drachenöde",
    ["Forest Song, Ashenvale"] = "Waldeslied, Eschental",
    ["Fort Wildervar, Howling Fjord"] = "Fort Wildervar, Heulender Fjord",
    ["Freewind Post, Thousand Needles"] = "Freiwindposten, Tausend Nadeln",
    ["Frosthold, The Storm Peaks"] = "Eisfestung, Die Sturmgipfel",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "Absturzstelle Grom'ash, Die Sturmgipfel",
    ["Grom'gol, Stranglethorn"] = "Grom'gol, Schlingendorntal",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "Höllenfeuerhalbinsel, das Dunkle Portal, Allianz",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "Höllenfeuerhalbinsel, das Dunkle Portal, Horde",
    ["Honor Hold, Hellfire Peninsula"] = "Ehrenfeste, Höllenfeuerhalbinsel",
    ["Ironforge, Dun Morogh"] = "Eisenschmiede, Dun Morogh",
    ["K3, The Storm Peaks"] = "K3, Die Sturmgipfel",
    ["Kamagua, Howling Fjord"] = "Kamagua, Heulender Fjord",
    ["Kargath, Badlands"] = "Kargath, Ödland",
    ["Kor'koron Vanguard, Dragonblight"] = "Vorposten der Kor'kron, Drachenöde",
    ["Lakeshire, Redridge"] = "Seenhain, Rotkammgebirge",
    ["Light's Breach, Zul'Drak"] = "Lichtbresche, Zul'Drak",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "Kapelle des hoffnungsvollen Lichts, Östliche Pestländer",
    ["Marshal's Refuge, Un'Goro Crater"] = "Marschalls Zuflucht, Krater von Un'Goro",
    ["Menethil Harbor, Wetlands"] = "Hafen von Menethil, Sumpfland",
    ["Moa'ki, Dragonblight"] = "Moa'ki, Drachenöde",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "Dorf der Mok'Nathal, Schergrat",
    ["Moonglade"] = "Mondlichtung",
    ["Morgan's Vigil, Burning Steppes"] = "Morgans Wacht, Brennende Steppe",
    ["Mudsprocket, Dustwallow Marsh"] = "Morastwinkel, Düstermarschen",
    ["Nesingwary Base Camp, Sholazar Basin"] = "Nesingwarys Basislager, Sholazarbecken",
    ["Nethergarde Keep, Blasted Lands"] = "Burg Nethergarde, Verwüstete Lande",
    ["New Agamand, Howling Fjord"] = "Neu-Agamand, Heulender Fjord",
    ["Nighthaven, Moonglade"] = "Nachthafen, Mondlichtung",
    ["Nijel's Point, Desolace"] = "Die Nijelspitze, Desolace",
    ["Northpass Tower, Eastern Plaguelands"] = "Nordpassturm, Östliche Pestländer",
    ["Orebor Harborage, Zangarmarsh"] = "Oreborzuflucht, Zangarmarschen",
    ["Plaguewood Tower, Eastern Plaguelands"] = "Pestwaldturm, Östliche Pestländer",
    ["Ratchet, The Barrens"] = "Ratschet, Brachland",
    ["Rebel Camp, Stranglethorn Vale"] = "Rebellenlager, Schlingendorntal",
    ["Refuge Pointe, Arathi"] = "Die Zuflucht, Arathi",
    ["Revantusk Village, The Hinterlands"] = "Dorf der Bruchhauer, Hinterland",
    ["River's Heart, Sholazar Basin"] = "Flussnabel, Sholazarbecken",
    ["Rut'theran Village, Teldrassil"] = "Rut'theran, Teldrassil",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "Sanktum der Sterne, Schattenmondtal",
    ["Sentinel Hill, Westfall"] = "Späherkuppe, Westfall",
    ["Shadowmoon Village, Shadowmoon Valley"] = "Schattenmond, Schattenmondtal",
    ["Shadowprey Village, Desolace"] = "Schattenflucht, Desolace",
    ["Shatter Point, Hellfire Peninsula"] = "Trümmerposten, Höllenfeuerhalbinsel",
    ["Shattered Sun Staging Area"] = "Sammelpunkt der Zerschmetterten Sonne",
    ["Shattrath, Terokkar Forest"] = "Shattrath, Wälder von Terokkar",
    ["Silvermoon City"] = "Silbermond",
    ["Southshore, Hillsbrad"] = "Süderstade, Hügelland",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "Rückenbrechergrat, Höllenfeuerhalbinsel",
    ["Splintertree Post, Ashenvale"] = "Splitterholzposten, Eschental",
    ["Stars' Rest, Dragonblight"] = "Sternenruh, Drachenöde",
    ["Stonard, Swamp of Sorrows"] = "Steinard, Sümpfe des Elends",
    ["Stonebreaker Hold, Terokkar Forest"] = "Steinbrecherfeste, Wälder von Terokkar",
    ["Stonetalon Peak, Stonetalon Mountains"] = "Steinkrallengipfel, Steinkrallengebirge",
    ["Stormwind, Elwynn"] = "Sturmwind, Elwynn",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "Sonnenfels, Steinkrallengebirge",
    ["Sunreaver's Command, Crystalsong Forest"] = "Sonnenhäschers Schar, Kristallsangwald",
    ["Swamprat Post, Zangarmarsh"] = "Sumpfrattenposten, Zangarmarschen",
    ["Sylvanaar, Blade's Edge Mountains"] = "Sylvanaar, Schergrat",
    ["Talonbranch Glade, Felwood"] = "Nachtlaublichtung, Teufelswald",
    ["Talrendis Point, Azshara"] = "Talrendisspitze, Azshara",
    ["Tarren Mill, Hillsbrad"] = "Tarrens Mühle, Hügelland",
    ["Taunka'le Village, Borean Tundra"] = "Taunka'le, Boreanische Tundra",
    ["Telredor, Zangarmarsh"] = "Telredor, Zangarmarschen",
    ["Temple of Telhamat, Hellfire Peninsula"] = "Tempel von Telhamat, Höllenfeuerhalbinsel",
    ["The Argent Vanguard, Icecrown"] = "Die Argentumvorhut, Eiskrone",
    ["The Bulwark, Tirisfal"] = "Das Bollwerk, Tirisfal",
    ["The Exodar"] = "Die Exodar",
    ["The Sepulcher, Silverpine Forest"] = "Das Grabmal, Silberwald",
    ["The Shadow Vault, Icecrown"] = "Das Schattengewölbe, Eiskrone",
    ["The Stormspire, Netherstorm"] = "Die Sturmsäule, Nethersturm",
    ["Theramore, Dustwallow Marsh"] = "Theramore, Düstermarschen",
    ["Thondoril River, Western Plaguelands"] = "Thondroril, Westliche Pestländer",
    ["Thorium Point, Searing Gorge"] = "Thoriumspitze, Sengende Schlucht",
    ["Thrallmar, Hellfire Peninsula"] = "Thrallmar, Höllenfeuerhalbinsel",
    ["Thunder Bluff, Mulgore"] = "Donnerfels, Mulgore",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "Donnerfeste, Schergrat",
    ["Toshley's Station, Blade's Edge Mountains"] = "Toshleys Station, Schergrat",
    ["Tranquillien, Ghostlands"] = "Tristessa, Geisterlande",
    ["Transitus Shield, Coldarra"] = "Transitusschild, Kaltarra",
    ["Ulduar, The Storm Peaks"] = "Ulduar, die Sturmgipfel",
    ["Undercity, Tirisfal"] = "Unterstadt, Tirisfal",
    ["Unu'pe, Borean Tundra"] = "Unu'pe, Boreanische Tundra",
    ["Valgarde Port, Howling Fjord"] = "Hafen von Valgarde, Heulender Fjord",
    ["Valiance Keep, Borean Tundra"] = "Valianzfeste, Boreanische Tundra",
    ["Valiance Landing Camp, Wintergrasp"] = "Valianzlager, Tausendwinter",
    ["Vengeance Landing, Howling Fjord"] = "Hafen der Vergeltung, Heulender Fjord",
    ["Venomspite, Dragonblight"] = "Gallgrimm, Drachenöde",
    ["Warsong Camp, Wintergrasp"] = "Kriegshymnenlager, Tausendwinter",
    ["Warsong Hold, Borean Tundra"] = "Kriegshymnenfeste, Boreanische Tundra",
    ["Westfall Brigade, Grizzly Hills"] = "Westfallbrigade, Grizzlyhügel",
    ["Westguard Keep, Howling Fjord"] = "Westwacht, Heulender Fjord",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "Wildhammerfeste, Schattenmondtal",
    ["Windrunner's Overlook, Crystalsong Forest"] = "Windläufers Warte, Kristallsangwald",
    ["Wintergarde Keep, Dragonblight"] = "Feste Wintergarde, Drachenöde",
    ["Wyrmrest Temple, Dragonblight"] = "Wyrmruhtempel, Drachenöde",
    ["Zabra'jin, Zangarmarsh"] = "Zabra'jin, Zangarmarschen",
    ["Zoram'gar Outpost, Ashenvale"] = "Außenposten von Zoram'gar, Eschental",
    ["Zul'Aman, Ghostlands"] = "Zul'Aman, Geisterlande",
  },
  ["esES"] = {
    ["Acherus: The Ebon Hold"] = "Acherus: El Bastión de Ébano",
    ["Aerie Peak, The Hinterlands"] = "Pico Nidal, Tierras del Interior",
    ["Agmar's Hammer, Dragonblight"] = "Martillo de Agmar, Cementerio de Dragones",
    ["Allerian Stronghold, Terokkar Forest"] = "Bastión Allerian, Bosque de Terokkar",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "Altar de Sha'tar, Valle Sombraluna",
    ["Amber Ledge, Borean Tundra"] = "El Saliente Ámbar, Tundra Boreal",
    ["Amberpine Lodge, Grizzly Hills"] = "Refugio Pino Ámbar, Colinas Pardas",
    ["Apothecary Camp, Howling Fjord"] = "Campamento de los Boticarios, Fiordo Aquilonal",
    ["Area 52, Netherstorm"] = "Área 52, Tormenta Abisal",
    ["Argent Stand, Zul'Drak"] = "El Confín Argenta, Zul'Drak",
    ["Argent Tournament Grounds, Icecrown"] = "Campos del Torneo Argenta, Corona de Hielo",
    ["Astranaar, Ashenvale"] = "Astranaar, Vallefresno",
    ["Auberdine, Darkshore"] = "Auberdine, Costa Oscura",
    ["Blood Watch, Bloodmyst Isle"] = "Avanzada de Sangre, Isla Bruma de Sangre",
    ["Bloodvenom Post, Felwood"] = "Puesto del Veneno",
    ["Booty Bay, Stranglethorn"] = "Bahía del Botín, Tuercespina",
    ["Bor'gorok Outpost, Borean Tundra"] = "Avanzada Bor'gorok, Tundra Boreal",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "Refugio de Pedruscón, Las Cumbres Tormentosas",
    ["Brackenwall Village, Dustwallow Marsh"] = "Poblado Murohelecho, Marjal Revolcafango",
    ["Camp Mojache, Feralas"] = "Campamento Mojache, Feralas",
    ["Camp Oneqwah, Grizzly Hills"] = "Campamento Oneqwah, Colinas Pardas",
    ["Camp Taurajo, The Barrens"] = "Campamento Taurajo, Los Baldíos",
    ["Camp Tunka'lo, The Storm Peaks"] = "Campamento Tunka'lo, Las Cumbres Tormentosas",
    ["Camp Winterhoof, Howling Fjord"] = "Campamento Pezuña Invernal, Fiordo Aquilonal",
    ["Cenarion Hold, Silithus"] = "Fuerte Cenarion, Silithus",
    ["Chillwind Camp, Western Plaguelands"] = "Campamento del Orvallo, Tierras de la Peste del Oeste",
    ["Cosmowrench, Netherstorm"] = "Cosmotirón, Tormenta Abisal",
    ["Crossroads, The Barrens"] = "El Cruce, Los Baldíos",
    ["Crown Guard Tower, Eastern Plaguelands"] = "Torre de la Corona, Tierras de la Peste del Este",
    ["Crusaders' Pinnacle, Icecrown"] = "Pináculo de los Cruzados, Corona de Hielo",
    ["Darkshire, Duskwood"] = "Villa Oscura, Bosque del Ocaso",
    ["Death's Rise, Icecrown"] = "Ascenso de la Muerte, Corona de Hielo",
    ["Dun Nifflelem, The Storm Peaks"] = "Dun Nifflelem, Las Cumbres Tormentosas",
    ["Eastwall Tower, Eastern Plaguelands"] = "Torre de la Muralla del Este, Tierras de la Peste del Este",
    ["Ebon Watch, Zul'Drak"] = "Puesto de Vigilancia de Ébano, Zul'Drak",
    ["Emerald Sanctuary, Felwood"] = "Santuario Esmeralda, Frondavil",
    ["Evergrove, Blade's Edge Mountains"] = "Soto Eterno, Montañas Filospada",
    ["Everlook, Winterspring"] = "Vista Eterna, Cuna del Invierno",
    ["Falcon Watch, Hellfire Peninsula"] = "Avanzada del Halcón, Península del Fuego Infernal",
    ["Feathermoon, Feralas"] = "Plumaluna, Feralas",
    ["Fishing Village, Teldrassil"] = "Aldea Pesquera, Teldrassil",
    ["Fizzcrank Airstrip, Borean Tundra"] = "Pista de Aterrizaje de Palanqueta, Tundra Boreal",
    ["Flame Crest, Burning Steppes"] = "Peñasco Llamarada, Las Estepas Ardientes",
    ["Fordragon Hold, Dragonblight"] = "Bastión de Fordragón, Cementerio de Dragones",
    ["Forest Song, Ashenvale"] = "Canción del Bosque, Vallefresno",
    ["Fort Wildervar, Howling Fjord"] = "Fuerte Vildervar, Fiordo Aquilonal",
    ["Freewind Post, Thousand Needles"] = "Poblado Viento Libre, Las Mil Agujas",
    ["Frosthold, The Storm Peaks"] = "Fuerte Escarcha, Las Cumbres Tormentosas",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "Lugar del accidente de Grom'arsh, Las Cumbres Tormentosas",
    ["Grom'gol, Stranglethorn"] = "Grom'gol, Tuercespina",
    ["Hammerfall, Arathi"] = "Sentencia, Arathi",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "Península del Fuego Infernal, El Portal Oscuro, Alianza",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "Península del Fuego Infernal, El Portal Oscuro, Horda",
    ["Honor Hold, Hellfire Peninsula"] = "Bastión del Honor, Península del Fuego Infernal",
    ["Ironforge, Dun Morogh"] = "Forjaz, Dun Morogh",
    ["K3, The Storm Peaks"] = "K3, Las Cumbres Tormentosas",
    ["Kamagua, Howling Fjord"] = "Komawa, Fiordo Aquilonal",
    ["Kargath, Badlands"] = "Kargath, Tierras Inhóspitas",
    ["Kor'koron Vanguard, Dragonblight"] = "Vanguardia Kor'kron, Cementerio de Dragones",
    ["Lakeshire, Redridge"] = "Villa del Lago, Crestagrana",
    ["Light's Breach, Zul'Drak"] = "Brecha de la Luz, Zul'Drak",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "Capilla de la Esperanza de la Luz, Tierras de la Peste del Este",
    ["Marshal's Refuge, Un'Goro Crater"] = "Refugio de Marshal, Cráter de Un'Goro",
    ["Menethil Harbor, Wetlands"] = "Puerto de Menethil, Los Humedales",
    ["Moa'ki, Dragonblight"] = "Moa'ki, Cementerio de Dragones",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "Aldea Mok'Nathal, Montañas Filospada",
    ["Moonglade"] = "Claro de la Luna",
    ["Morgan's Vigil, Burning Steppes"] = "Vigilia de Morgan, Las Estepas Ardientes",
    ["Mudsprocket, Dustwallow Marsh"] = "Piñón de Barro, Marjal Revolcafango",
    ["Nesingwary Base Camp, Sholazar Basin"] = "Campamento Base de Nesingwary, Cuenca de Sholazar",
    ["Nethergarde Keep, Blasted Lands"] = "Castillo de Nethergarde, Las Tierras Devastadas",
    ["New Agamand, Howling Fjord"] = "Nuevo Agamand, Fiordo Aquilonal",
    ["Nighthaven, Moonglade"] = "Amparo de la Noche, Claro de la Luna",
    ["Nijel's Point, Desolace"] = "Punta de Nijel, Desolace",
    ["Northpass Tower, Eastern Plaguelands"] = "Torre del Paso Norte, Tierras de la Peste del Este",
    ["Ogri'La"] = "Ogri'la",
    ["Orebor Harborage, Zangarmarsh"] = "Puerto Orebor, Marisma de Zangar",
    ["Plaguewood Tower, Eastern Plaguelands"] = "Torre del Bosque de la Peste, Tierras de la Peste de Este",
    ["Ratchet, The Barrens"] = "Trinquete, Los Baldíos",
    ["Rebel Camp, Stranglethorn Vale"] = "Asentamiento Rebelde, Vega de Tuercespina",
    ["Refuge Pointe, Arathi"] = "Refugio de la Zaga, Arathi",
    ["Revantusk Village, The Hinterlands"] = "Poblado Sañadiente, Tierras del Interior",
    ["River's Heart, Sholazar Basin"] = "Corazón del Río, Cuenca de Sholazar",
    ["Rut'theran Village, Teldrassil"] = "Aldea Rut'theran, Teldrassil",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "Sagrario de las Estrellas, Valle Sombraluna",
    ["Sentinel Hill, Westfall"] = "Colina del Centinela, Páramos de Poniente",
    ["Shadowmoon Village, Shadowmoon Valley"] = "Aldea Sombraluna, Valle Sombraluna",
    ["Shadowprey Village, Desolace"] = "Aldea Cazasombras, Desolace",
    ["Shatter Point, Hellfire Peninsula"] = "Puesto Devastación, Península del Fuego Infernal",
    ["Shattered Sun Staging Area"] = "Zona de escala de Sol Devastado",
    ["Shattrath, Terokkar Forest"] = "Shattrath, Bosque de Terokkar",
    ["Silvermoon City"] = "Ciudad de Lunargenta",
    ["Southshore, Hillsbrad"] = "Costasur, Trabalomas",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "Cresta Rompeloma, Península del Fuego Infernal",
    ["Splintertree Post, Ashenvale"] = "Puesto del Hachazo, Vallefresno",
    ["Stars' Rest, Dragonblight"] = "Reposo Estelar, Cementerio de Dragones",
    ["Stonard, Swamp of Sorrows"] = "Rocal, Pantano de las Penas",
    ["Stonebreaker Hold, Terokkar Forest"] = "Bastión Rompepedras, Bosque de Terokkar",
    ["Stonetalon Peak, Stonetalon Mountains"] = "Cima del Espolón, Sierra Espolón",
    ["Stormwind, Elwynn"] = "Ventormenta, Elwynn",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "Refugio Roca del Sol, Sierra Espolón",
    ["Sunreaver's Command, Crystalsong Forest"] = "Dominio de los Atracasol, Bosque Canto de Cristal",
    ["Swamprat Post, Zangarmarsh"] = "Avanzada Rata del Pantano, Marisma de Zangar",
    ["Sylvanaar, Blade's Edge Mountains"] = "Sylvanaar, Montañas Filospada",
    ["Talonbranch Glade, Felwood"] = "Claro Ramaespolón, Frondavil",
    ["Talrendis Point, Azshara"] = "Punta Talrendis, Azshara",
    ["Tarren Mill, Hillsbrad"] = "Molino Tarren, Trabalomas",
    ["Taunka'le Village, Borean Tundra"] = "Poblado Taunka'le, Tundra Boreal",
    ["Telredor, Zangarmarsh"] = "Telredor, Marisma de Zangar",
    ["Temple of Telhamat, Hellfire Peninsula"] = "Templo de Telhamat, Península del Fuego Infernal",
    ["The Argent Vanguard, Icecrown"] = "La Vanguardia Argenta, Corona de Hielo",
    ["The Bulwark, Tirisfal"] = "El Baluarte, Tirisfal",
    ["The Exodar"] = "El Exodar",
    ["The Sepulcher, Silverpine Forest"] = "El Sepulcro, Bosque de Argénteos",
    ["The Shadow Vault, Icecrown"] = "La Cámara de las Sombras, Corona de Hielo",
    ["The Stormspire, Netherstorm"] = "La Flecha de la Tormenta, Tormenta Abisal",
    ["Theramore, Dustwallow Marsh"] = "Theramore, Marjal Revolcafango",
    ["Thondoril River, Western Plaguelands"] = "Río Thondroril, Tierras de la Peste del Oeste",
    ["Thorium Point, Searing Gorge"] = "Puesto del Torio, La Garganta de Fuego",
    ["Thrallmar, Hellfire Peninsula"] = "Thrallmar, Península del Fuego Infernal",
    ["Thunder Bluff, Mulgore"] = "Cima del Trueno, Mulgore",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "Bastión Señor del Trueno, Montañas Filospada",
    ["Toshley's Station, Blade's Edge Mountains"] = "Estación de Toshley, Montañas Filospada",
    ["Tranquillien, Ghostlands"] = "Tranquilien, Tierras Fantasma",
    ["Transitus Shield, Coldarra"] = "Escudo de Tránsito, Gelidar",
    ["Ulduar, The Storm Peaks"] = "Ulduar, Las Cumbres Tormentosas",
    ["Undercity, Tirisfal"] = "Entrañas, Tirisfal",
    ["Unu'pe, Borean Tundra"] = "Unu'pe, Tundra Boreal",
    ["Valgarde Port, Howling Fjord"] = "Puerto de Valgarde, Fiordo Aquilonal",
    ["Valiance Keep, Borean Tundra"] = "Fortaleza Denuedo, Tundra Boreal",
    ["Valiance Landing Camp, Wintergrasp"] = "Campamento de Aterrizaje de Denuedo, Conquista del Invierno",
    ["Vengeance Landing, Howling Fjord"] = "Campo Venganza, Fiordo Aquilonal",
    ["Venomspite, Dragonblight"] = "Rencor Venenoso, Cementerio de Dragones",
    ["Warsong Camp, Wintergrasp"] = "Campamento Grito de Guerra, Conquista del Invierno",
    ["Warsong Hold, Borean Tundra"] = "Bastión Grito de Guerra, Tundra Boreal",
    ["Westfall Brigade, Grizzly Hills"] = "Brigada de los Páramos de Poniente, Colinas Pardas",
    ["Westguard Keep, Howling Fjord"] = "Fortaleza de la Guardia Oeste, Fiordo Aquilonal",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "Bastión Martillo Salvaje, Valle Sombraluna",
    ["Windrunner's Overlook, Crystalsong Forest"] = "Mirador Brisaveloz, Bosque Canto de Cristal",
    ["Wintergarde Keep, Dragonblight"] = "Fortaleza de Hibergarde, Cementerio de Dragones",
    ["Wyrmrest Temple, Dragonblight"] = "Templo del Reposo del Dragón, Cementerio de Dragones",
    ["Zabra'jin, Zangarmarsh"] = "Zabra'jin, Marisma de Zangar",
    ["Zoram'gar Outpost, Ashenvale"] = "Avanzada de Zoram'gar, Vallefresno",
    ["Zul'Aman, Ghostlands"] = "Zul'Aman, Tierras Fantasma",
  },
  ["frFR"] = {
    ["Acherus: The Ebon Hold"] = "Achérus : le fort d'Ébène",
    ["Aerie Peak, The Hinterlands"] = "Nid-de-l'Aigle, les Hinterlands",
    ["Agmar's Hammer, Dragonblight"] = "Marteau d'Agmar, Désolation des dragons",
    ["Allerian Stronghold, Terokkar Forest"] = "Bastion allérien, forêt de Terokkar",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "Autel de Sha'tar, vallée d'Ombrelune",
    ["Amber Ledge, Borean Tundra"] = "Escarpement d'Ambre, toundra Boréenne",
    ["Amberpine Lodge, Grizzly Hills"] = "Gîte Ambrepin, les Grisonnes",
    ["Apothecary Camp, Howling Fjord"] = "Camp des Apothicaires, fjord Hurlant",
    ["Area 52, Netherstorm"] = "Zone 52, Raz-de-Néant",
    ["Argent Stand, Zul'Drak"] = "Séjour d'Argent, Zul'Drak",
    ["Argent Tournament Grounds, Icecrown"] = "Enceinte du tournoi d'Argent, Couronne de glace",
    ["Astranaar, Ashenvale"] = "Astranaar, Orneval",
    ["Auberdine, Darkshore"] = "Auberdine, Sombrivage",
    ["Blood Watch, Bloodmyst Isle"] = "Guet du sang, île de Brume-sang",
    ["Bloodvenom Post, Felwood"] = "Poste de la Vénéneuse, Gangrebois",
    ["Booty Bay, Stranglethorn"] = "Baie-du-Butin, Strangleronce",
    ["Bor'gorok Outpost, Borean Tundra"] = "Avant-poste Bor'gorok, toundra Boréenne",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "Refuge de Rochecombe, les pics Foudroyés",
    ["Brackenwall Village, Dustwallow Marsh"] = "Mur-de-Fougères, marécage d'Âprefange",
    ["Camp Mojache, Feralas"] = "Camp Mojache, Féralas",
    ["Camp Oneqwah, Grizzly Hills"] = "Camp Oneqwah, les Grisonnes",
    ["Camp Taurajo, The Barrens"] = "Camp Taurajo, les Tarides",
    ["Camp Tunka'lo, The Storm Peaks"] = "Camp Tunka'lo, les pics Foudroyés",
    ["Camp Winterhoof, Howling Fjord"] = "Camp Sabot-d'hiver, fjord Hurlant",
    ["Cenarion Hold, Silithus"] = "Fort cénarien, Silithus",
    ["Chillwind Camp, Western Plaguelands"] = "Camp du Noroît, Maleterres de l'ouest",
    ["Cosmowrench, Netherstorm"] = "Cosmovrille, Raz-de-Néant",
    ["Crossroads, The Barrens"] = "La Croisée, Tarides",
    ["Crown Guard Tower, Eastern Plaguelands"] = "Tour de garde de la couronne, Maleterres de l'est",
    ["Crusaders' Pinnacle, Icecrown"] = "Cime des Croisés, Couronne de glace",
    ["Darkshire, Duskwood"] = "Sombre-comté, bois de la Pénombre",
    ["Death's Rise, Icecrown"] = "Cime de la Mort, Couronne de glace",
    ["Dun Nifflelem, The Storm Peaks"] = "Dun Nifflelem, les pics Foudroyés",
    ["Eastwall Tower, Eastern Plaguelands"] = "Tour du Mur d'est, Maleterres de l'est",
    ["Ebon Watch, Zul'Drak"] = "Guet d'Ébène, Zul'Drak",
    ["Emerald Sanctuary, Felwood"] = "Sanctuaire d'émeraude, Gangrebois",
    ["Evergrove, Blade's Edge Mountains"] = "Bosquet éternel, les Tranchantes",
    ["Everlook, Winterspring"] = "Long-guet, Berceau-de-l'Hiver",
    ["Falcon Watch, Hellfire Peninsula"] = "Guet de l'épervier, péninsule des Flammes infernales",
    ["Feathermoon, Feralas"] = "Pennelune, Féralas",
    ["Fishing Village, Teldrassil"] = "Village de pêcheurs, Teldrassil",
    ["Fizzcrank Airstrip, Borean Tundra"] = "Piste d'atterrissage de Spumelevier, toundra Boréenne",
    ["Flame Crest, Burning Steppes"] = "Corniche des flammes, Steppes ardentes",
    ["Fordragon Hold, Dragonblight"] = "Bastion Fordragon, Désolation des dragons",
    ["Forest Song, Ashenvale"] = "Chant des forêts, Orneval",
    ["Fort Wildervar, Howling Fjord"] = "Fort Hardivar, fjord Hurlant",
    ["Freewind Post, Thousand Needles"] = "Poste de Librevent, Mille Pointes",
    ["Frosthold, The Storm Peaks"] = "Fort du Givre, les pics Foudroyés",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "Point d'impact de Grom'arsh, les pics Foudroyés",
    ["Grom'gol, Stranglethorn"] = "Grom'gol, Strangleronce",
    ["Hammerfall, Arathi"] = "Trépas-d'Orgrim, Arathi",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "Péninsule des Flammes infernales, Porte des ténèbres, Alliance",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "Péninsule des Flammes infernales, Porte des ténèbres, Horde",
    ["Honor Hold, Hellfire Peninsula"] = "Bastion de l'Honneur, péninsule des Flammes infernales",
    ["Ironforge, Dun Morogh"] = "Forgefer, Dun Morogh",
    ["K3, The Storm Peaks"] = "K3, les pics Foudroyés",
    ["Kamagua, Howling Fjord"] = "Kamagua, fjord Hurlant",
    ["Kargath, Badlands"] = "Kargath, Terres ingrates",
    ["Kor'koron Vanguard, Dragonblight"] = "Avant-garde kor'kronne, Désolation des dragons",
    ["Lakeshire, Redridge"] = "Comté-du-lac, les Carmines",
    ["Light's Breach, Zul'Drak"] = "La Brèche de Lumière, Zul'Drak",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "Chapelle de l'Espoir de Lumière, Maleterres de l'est",
    ["Marshal's Refuge, Un'Goro Crater"] = "Refuge des Marshal, cratère d'Un'Goro",
    ["Menethil Harbor, Wetlands"] = "Port de Menethil, les Paluns",
    ["Moa'ki, Dragonblight"] = "Moa'ki, Désolation des dragons",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "Mok'Nathal, les Tranchantes",
    ["Moonglade"] = "Reflet-de-Lune",
    ["Morgan's Vigil, Burning Steppes"] = "Veille de Morgan, Steppes ardentes",
    ["Mudsprocket, Dustwallow Marsh"] = "Bourbe-à-brac, marécage d'Âprefange",
    ["Nesingwary Base Camp, Sholazar Basin"] = "Camp de base de Nesingwary, bassin de Sholazar",
    ["Nethergarde Keep, Blasted Lands"] = "Rempart-du-Néant, Terres foudroyées",
    ["New Agamand, Howling Fjord"] = "Nouvelle-Agamand, fjord Hurlant",
    ["Nighthaven, Moonglade"] = "Havrenuit, Reflet-de-Lune",
    ["Nijel's Point, Desolace"] = "Combe de Nijel, Désolace",
    ["Northpass Tower, Eastern Plaguelands"] = "Tour du Col du nord, Maleterres de l'est",
    ["Orebor Harborage, Zangarmarsh"] = "Havre d'Orebor, marécage de Zangar",
    ["Plaguewood Tower, Eastern Plaguelands"] = "Tour de Pestebois, Maleterres de l'est",
    ["Ratchet, The Barrens"] = "Cabestan, les Tarides",
    ["Rebel Camp, Stranglethorn Vale"] = "Camp rebelle, vallée de Strangleronce",
    ["Refuge Pointe, Arathi"] = "Refuge de l'Ornière, Arathi",
    ["Revantusk Village, The Hinterlands"] = "Village des Vengebroches, les Hinterlands",
    ["River's Heart, Sholazar Basin"] = "Le Cœur du fleuve, bassin de Sholazar",
    ["Rut'theran Village, Teldrassil"] = "Rut'theran, Teldrassil",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "Sanctum des étoiles, vallée d'Ombrelune",
    ["Sentinel Hill, Westfall"] = "Colline des sentinelles, marche de l'Ouest",
    ["Shadowmoon Village, Shadowmoon Valley"] = "Village d'Ombrelune, vallée d'Ombrelune",
    ["Shadowprey Village, Desolace"] = "Proie-de-l'Ombre, Désolace",
    ["Shatter Point, Hellfire Peninsula"] = "Halte du Fracas, péninsule des Flammes infernales",
    ["Shattered Sun Staging Area"] = "Zone de rassemblement du Soleil brisé",
    ["Shattrath, Terokkar Forest"] = "Shattrath, forêt de Terokkar",
    ["Silvermoon City"] = "Lune-d'argent",
    ["Southshore, Hillsbrad"] = "Austrivage, Hautebrande",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "Crête Brise-échine, péninsule des Flammes infernales",
    ["Splintertree Post, Ashenvale"] = "Poste de Bois-brisé, Orneval",
    ["Stars' Rest, Dragonblight"] = "Repos des étoiles, Désolation des dragons",
    ["Stonard, Swamp of Sorrows"] = "Pierrêche, marais des Chagrins",
    ["Stonebreaker Hold, Terokkar Forest"] = "Fort des Brise-pierres, forêt de Terokkar",
    ["Stonetalon Peak, Stonetalon Mountains"] = "Pic des Serres-Rocheuses, Serres-Rocheuses",
    ["Stormwind, Elwynn"] = "Hurlevent, Elwynn",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "Retraite de Roche-Soleil, Serres-Rocheuses",
    ["Sunreaver's Command, Crystalsong Forest"] = "Quartier général de Saccage-soleil, forêt du Chant de cristal",
    ["Swamprat Post, Zangarmarsh"] = "Poste du Rat des marais, marécage de Zangar",
    ["Sylvanaar, Blade's Edge Mountains"] = "Sylvanaar, les Tranchantes",
    ["Talonbranch Glade, Felwood"] = "Clairière de Griffebranche, Gangrebois",
    ["Talrendis Point, Azshara"] = "Halte de Talrendis, Azshara",
    ["Tarren Mill, Hillsbrad"] = "Moulin-de-Tarren, Hautebrande",
    ["Taunka'le Village, Borean Tundra"] = "Taunka'le, toundra Boréenne",
    ["Telredor, Zangarmarsh"] = "Telredor, marécage de Zangar",
    ["Temple of Telhamat, Hellfire Peninsula"] = "Temple de Telhamat, péninsule des Flammes infernales",
    ["Thalanaar, Feralas"] = "Thalanaar, Féralas",
    ["The Argent Vanguard, Icecrown"] = "L'avant-garde d'Argent, Couronne de glace",
    ["The Bulwark, Tirisfal"] = "La Barricade, Clairières de Tirisfal",
    ["The Exodar"] = "L'Exodar",
    ["The Sepulcher, Silverpine Forest"] = "Le Sépulcre, forêt des Pins argentés",
    ["The Shadow Vault, Icecrown"] = "Le caveau des Ombres, Couronne de glace",
    ["The Stormspire, Netherstorm"] = "La Foudreflèche, Raz-de-Néant",
    ["Theramore, Dustwallow Marsh"] = "Theramore, marécage d'Âprefange",
    ["Thondoril River, Western Plaguelands"] = "La Thondroril, Maleterres de l'ouest",
    ["Thorium Point, Searing Gorge"] = "Halte du Thorium, gorge des Vents brûlants",
    ["Thrallmar, Hellfire Peninsula"] = "Thrallmar, péninsule des Flammes infernales",
    ["Thunder Bluff, Mulgore"] = "Les Pitons du Tonnerre, Mulgore",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "Bastion des Sire-tonnerre, les Tranchantes",
    ["Toshley's Station, Blade's Edge Mountains"] = "Poste de Toshley, les Tranchantes",
    ["Tranquillien, Ghostlands"] = "Tranquillien, Terres fantômes",
    ["Transitus Shield, Coldarra"] = "Bouclier Transitus, Frimarra",
    ["Ulduar, The Storm Peaks"] = "Ulduar, les pics Foudroyés",
    ["Undercity, Tirisfal"] = "Fossoyeuse, Tirisfal",
    ["Unu'pe, Borean Tundra"] = "Unu'pe, toundra Boréenne",
    ["Valgarde Port, Howling Fjord"] = "Port-Valgarde",
    ["Valiance Keep, Borean Tundra"] = "Donjon de la Bravoure, toundra Boréenne",
    ["Valiance Landing Camp, Wintergrasp"] = "Terrain d'atterrissage de la Bravoure, Joug-d'hiver",
    ["Vengeance Landing, Howling Fjord"] = "Accostage de la Vengeance, fjord Hurlant",
    ["Venomspite, Dragonblight"] = "Vexevenin, Désolation des dragons",
    ["Warsong Camp, Wintergrasp"] = "Camp chanteguerre, Joug-d'hiver",
    ["Warsong Hold, Borean Tundra"] = "Bastion Chanteguerre, toundra Boréenne",
    ["Westfall Brigade, Grizzly Hills"] = "Brigade de la marche de l'Ouest, les Grisonnes",
    ["Westguard Keep, Howling Fjord"] = "Donjon de la Garde de l'ouest, fjord Hurlant",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "Bastion Marteau-hardi, vallée d'Ombrelune",
    ["Windrunner's Overlook, Crystalsong Forest"] = "Surplomb de Coursevent, forêt du Chant de cristal",
    ["Wintergarde Keep, Dragonblight"] = "Donjon de Garde-hiver, Désolation des dragons",
    ["Wyrmrest Temple, Dragonblight"] = "Temple du Repos du ver, Désolation des dragons",
    ["Zabra'jin, Zangarmarsh"] = "Zabra'jin, marécage de Zangar",
    ["Zoram'gar Outpost, Ashenvale"] = "Avant-poste de Zoram'gar, Orneval",
    ["Zul'Aman, Ghostlands"] = "Zul'Aman, Terres fantômes",
  },
  ["koKR"] = {
    ["Acherus: The Ebon Hold"] = "아케루스: 칠흑의 요새",
    ["Aerie Peak, The Hinterlands"] = "맹금의 봉우리 (동부 내륙지)",
    ["Agmar's Hammer, Dragonblight"] = "아그마르의 망치 (용의 안식처)",
    ["Allerian Stronghold, Terokkar Forest"] = "알레리아 성채 (테로카르 숲)",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "샤타르 제단 (어둠달 골짜기)",
    ["Amber Ledge, Borean Tundra"] = "호박석 절벽 (북풍의 땅)",
    ["Amberpine Lodge, Grizzly Hills"] = "호박빛소나무 오두막 (회색 구릉지)",
    ["Apothecary Camp, Howling Fjord"] = "연금술사 야영지 (울부짖는 협만)",
    ["Area 52, Netherstorm"] = "52번 구역 (황천의 폭풍)",
    ["Argent Stand, Zul'Drak"] = "은빛십자군 격전지 (줄드락)",
    ["Argent Tournament Grounds, Icecrown"] = "은빛십자군 마상시합 광장, 얼음왕관",
    ["Astranaar, Ashenvale"] = "아스트라나르 (잿빛 골짜기)",
    ["Auberdine, Darkshore"] = "아우버다인 (어둠의 해안)",
    ["Blood Watch, Bloodmyst Isle"] = "핏빛 감시초소 (핏빛안개 섬)",
    ["Bloodvenom Post, Felwood"] = "피멍울 초소 (악령의 숲)",
    ["Booty Bay, Stranglethorn"] = "무법항 (가시덤불 골짜기)",
    ["Bor'gorok Outpost, Borean Tundra"] = "보르고로크 전초기지 (북풍의 땅)",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "바울더크랙의 은거처 (폭풍우 봉우리)",
    ["Brackenwall Village, Dustwallow Marsh"] = "담쟁이 마을 (먼지진흙 습지대)",
    ["Camp Mojache, Feralas"] = "모자케 야영지 (페랄라스)",
    ["Camp Oneqwah, Grizzly Hills"] = "원크와 야영지 (회색 구릉지)",
    ["Camp Taurajo, The Barrens"] = "타우라조 야영지 (불모의 땅)",
    ["Camp Tunka'lo, The Storm Peaks"] = "툰카로 야영지 (폭풍우 봉우리)",
    ["Camp Winterhoof, Howling Fjord"] = "겨울발굽 야영지 (울부짖는 협만)",
    ["Cenarion Hold, Silithus"] = "세나리온 요새 (실리더스)",
    ["Chillwind Camp, Western Plaguelands"] = "서리바람 야영지 (서부 역병지대)",
    ["Cosmowrench, Netherstorm"] = "코스모렌치 (황천의 폭풍)",
    ["Crossroads, The Barrens"] = "크로스로드 (불모의 땅)",
    ["Crown Guard Tower, Eastern Plaguelands"] = "산마루 경비탑 (동부 역병지대)",
    ["Crusaders' Pinnacle, Icecrown"] = "십자군 봉우리 (얼음왕관)",
    ["Dalaran"] = "달라란",
    ["Darkshire, Duskwood"] = "다크샤이어 (그늘숲)",
    ["Death's Rise, Icecrown"] = "죽음의 마루 (얼음왕관)",
    ["Dun Nifflelem, The Storm Peaks"] = "던 니펠렘 (폭풍우 봉우리)",
    ["Eastwall Tower, Eastern Plaguelands"] = "동부방벽 경비탑 (동부 역병지대)",
    ["Ebon Watch, Zul'Drak"] = "칠흑의 감시초소 (줄드락)",
    ["Emerald Sanctuary, Felwood"] = "에메랄드 성소 (악령의 숲)",
    ["Evergrove, Blade's Edge Mountains"] = "영원의 숲 (칼날 산맥)",
    ["Everlook, Winterspring"] = "눈망루 마을 (여명의 설원)",
    ["Falcon Watch, Hellfire Peninsula"] = "매의 감시탑 (지옥불 반도)",
    ["Feathermoon, Feralas"] = "페더문 요새 (페랄라스)",
    ["Fishing Village, Teldrassil"] = "고기잡이 마을 (텔드랏실)",
    ["Fizzcrank Airstrip, Borean Tundra"] = "피즈크랭크 비행장 (북풍의 땅)",
    ["Flame Crest, Burning Steppes"] = "화염 마루 (불타는 평원)",
    ["Fordragon Hold, Dragonblight"] = "폴드라곤 요새 (용의 안식처)",
    ["Forest Song, Ashenvale"] = "숲의 노래 (잿빛 골짜기)",
    ["Fort Wildervar, Howling Fjord"] = "빌더바르 요새 (울부짖는 협만)",
    ["Freewind Post, Thousand Needles"] = "높새바람 봉우리 (버섯구름 봉우리)",
    ["Frosthold, The Storm Peaks"] = "서리요새 (폭풍우 봉우리)",
    ["Gadgetzan, Tanaris"] = "가젯잔 (타나리스)",
    ["Garadar, Nagrand"] = "가라다르 (나그란드)",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "그롬마쉬 추락 지점 (폭풍우 봉우리)",
    ["Grom'gol, Stranglethorn"] = "그롬골 (가시덤불 골짜기)",
    ["Gundrak, Zul'Drak"] = "군드락 (줄드락)",
    ["Hammerfall, Arathi"] = "해머폴 (아라시 고원)",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "어둠의 문 (지옥불 반도, 얼라이언스)",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "어둠의 문 (지옥불 반도, 호드)",
    ["Honor Hold, Hellfire Peninsula"] = "명예의 요새 (지옥불 반도)",
    ["Ironforge, Dun Morogh"] = "아이언포지 (던 모로)",
    ["K3, The Storm Peaks"] = "K3 (폭풍우 봉우리)",
    ["Kamagua, Howling Fjord"] = "카마구아 (울부짖는 협만)",
    ["Kargath, Badlands"] = "카르가스 (황야의 땅)",
    ["Kor'koron Vanguard, Dragonblight"] = "코르크론 선봉기지 (용의 안식처)",
    ["Lakeshire, Redridge"] = "레이크샤이어 (붉은마루 산맥)",
    ["Light's Breach, Zul'Drak"] = "빛의 틈 (줄드락)",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "희망의 빛 예배당 (동부 역병지대)",
    ["Marshal's Refuge, Un'Goro Crater"] = "마샬의 야영지 (운고로 분화구)",
    ["Menethil Harbor, Wetlands"] = "메네실 항구 (저습지)",
    ["Moa'ki, Dragonblight"] = "모아키 항구 (용의 안식처)",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "모크나탈 마을 (칼날 산맥)",
    ["Moonglade"] = "달의 숲",
    ["Morgan's Vigil, Burning Steppes"] = "모건의 망루 (불타는 평원)",
    ["Mudsprocket, Dustwallow Marsh"] = "진흙톱니 거점 (먼지진흙 습지대)",
    ["Nesingwary Base Camp, Sholazar Basin"] = "네싱워리 주둔지 (숄라자르 분지)",
    ["Nethergarde Keep, Blasted Lands"] = "네더가드 요새 (저주받은 땅)",
    ["New Agamand, Howling Fjord"] = "신 아가만드 (울부짖는 협만)",
    ["Nighthaven, Moonglade"] = "나이트헤이븐 (달의 숲)",
    ["Nijel's Point, Desolace"] = "나이젤의 야영지 (잊혀진 땅)",
    ["Northpass Tower, Eastern Plaguelands"] = "북부관문 경비탑 (동부 역병지대)",
    ["Ogri'La"] = "오그릴라",
    ["Orebor Harborage, Zangarmarsh"] = "오레보르 피난처 (장가르 습지대)",
    ["Orgrimmar, Durotar"] = "오그리마 (듀로타)",
    ["Plaguewood Tower, Eastern Plaguelands"] = "역병의 숲 경비탑 (동부 역병지대)",
    ["Ratchet, The Barrens"] = "톱니항 (불모의 땅)",
    ["Rebel Camp, Stranglethorn Vale"] = "반란군 야영지 (가시덤불 골짜기)",
    ["Refuge Pointe, Arathi"] = "임시 주둔지 (아라시 고원)",
    ["Revantusk Village, The Hinterlands"] = "레반터스크 마을 (동부 내륙지)",
    ["River's Heart, Sholazar Basin"] = "강의 심장부 (숄라자르 분지)",
    ["Rut'theran Village, Teldrassil"] = "루테란 마을 (텔드랏실)",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "별의 성소 (어둠달 골짜기)",
    ["Sentinel Hill, Westfall"] = "감시의 언덕 (서부 몰락지대)",
    ["Shadowmoon Village, Shadowmoon Valley"] = "어둠달 마을 (어둠달 골짜기)",
    ["Shadowprey Village, Desolace"] = "그늘수렵 마을 (잊혀진 땅)",
    ["Shatter Point, Hellfire Peninsula"] = "징검다리 거점 (지옥불 반도)",
    ["Shattered Sun Staging Area"] = "무너진 태양 집결지",
    ["Shattrath, Terokkar Forest"] = "샤트라스 (테로카르 숲)",
    ["Silvermoon City"] = "실버문",
    ["Skettis"] = "스케티스",
    ["Southshore, Hillsbrad"] = "사우스쇼어 (힐스브래드 구릉지)",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "해골망치 마루 (지옥불 반도)",
    ["Splintertree Post, Ashenvale"] = "토막나무 주둔지 (잿빛 골짜기)",
    ["Stars' Rest, Dragonblight"] = "별의 쉼터 (용의 안식처)",
    ["Stonard, Swamp of Sorrows"] = "스토나드 (슬픔의 늪)",
    ["Stonebreaker Hold, Terokkar Forest"] = "돌망치 요새 (테로카르 숲)",
    ["Stonetalon Peak, Stonetalon Mountains"] = "돌발톱 봉우리 (돌발톱 산맥)",
    ["Stormwind, Elwynn"] = "스톰윈드 (엘윈 숲)",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "해바위 야영지, 돌발톱 산맥",
    ["Sunreaver's Command, Crystalsong Forest"] = "선리버 지휘초소 (수정노래 숲)",
    ["Swamprat Post, Zangarmarsh"] = "늪쥐 감시초소 (장가르 습지대)",
    ["Sylvanaar, Blade's Edge Mountains"] = "실바나르 (칼날 산맥)",
    ["Talonbranch Glade, Felwood"] = "갈퀴가지 숲 (악령의 숲)",
    ["Talrendis Point, Azshara"] = "탈렌드리스 초소 (아즈샤라)",
    ["Tarren Mill, Hillsbrad"] = "타렌 밀농장 (힐스브래드 구릉지)",
    ["Taunka'le Village, Borean Tundra"] = "타운카르 마을 (북풍의 땅)",
    ["Telaar, Nagrand"] = "텔라아르 (나그란드)",
    ["Telredor, Zangarmarsh"] = "텔레도르 (장가르 습지대)",
    ["Temple of Telhamat, Hellfire Peninsula"] = "텔하마트 사원 (지옥불 반도)",
    ["Thalanaar, Feralas"] = "탈라나르 (페랄라스)",
    ["The Argent Vanguard, Icecrown"] = "은빛십자군 선봉기지 (얼음왕관)",
    ["The Bulwark, Tirisfal"] = "보루 (티리스팔 숲)",
    ["The Exodar"] = "엑소다르",
    ["The Sepulcher, Silverpine Forest"] = "공동묘지 (은빛소나무 숲)",
    ["The Shadow Vault, Icecrown"] = "어둠의 무기고 (얼음왕관)",
    ["The Stormspire, Netherstorm"] = "폭풍 첨탑 (황천의 폭풍)",
    ["Thelsamar, Loch Modan"] = "텔사마 (모단 호수)",
    ["Theramore, Dustwallow Marsh"] = "테라모어 섬 (먼지진흙 습지대)",
    ["Thondoril River, Western Plaguelands"] = "톤드로릴 강 (서부 역병지대)",
    ["Thorium Point, Searing Gorge"] = "토륨 조합 거점 (이글거리는 협곡)",
    ["Thrallmar, Hellfire Peninsula"] = "스랄마 (지옥불 반도)",
    ["Thunder Bluff, Mulgore"] = "썬더 블러프 (멀고어)",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "천둥군주 요새 (칼날 산맥)",
    ["Toshley's Station, Blade's Edge Mountains"] = "토쉴리의 연구기지 (칼날 산맥)",
    ["Tranquillien, Ghostlands"] = "트랜퀼리엔 (유령의 땅)",
    ["Transitus Shield, Coldarra"] = "변위의 보호막 (콜다라)",
    ["Ulduar, The Storm Peaks"] = "울두아르 (폭풍우 봉우리)",
    ["Undercity, Tirisfal"] = "언더시티 (티리스팔 숲)",
    ["Unu'pe, Borean Tundra"] = "우누페 (북풍의 땅)",
    ["Valgarde Port, Howling Fjord"] = "발가드 항만 (울부짖는 협만)",
    ["Valiance Keep, Borean Tundra"] = "용맹의 성채 (북풍의 땅)",
    ["Valiance Landing Camp, Wintergrasp"] = "용맹의 주둔지 (겨울손아귀 호수)",
    ["Valormok, Azshara"] = "발로르모크 (아즈샤라)",
    ["Vengeance Landing, Howling Fjord"] = "복수의 상륙지 (울부짖는 협만)",
    ["Venomspite, Dragonblight"] = "원한의 초소 (용의 안식처)",
    ["Warsong Camp, Wintergrasp"] = "전쟁노래부족 야영지 (겨울손아귀)",
    ["Warsong Hold, Borean Tundra"] = "전쟁노래부족 요새 (북풍의 땅)",
    ["Westfall Brigade, Grizzly Hills"] = "서부 몰락지대 여단 (회색 구릉지)",
    ["Westguard Keep, Howling Fjord"] = "서부경비대 성채 (울부짖는 협만)",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "와일드해머 성채 (어둠달 골짜기)",
    ["Windrunner's Overlook, Crystalsong Forest"] = "윈드러너 전망대 (수정노래 숲)",
    ["Wintergarde Keep, Dragonblight"] = "윈터가드 성채 (용의 안식처)",
    ["Wyrmrest Temple, Dragonblight"] = "고룡쉼터 사원 (용의 안식처)",
    ["Zabra'jin, Zangarmarsh"] = "자브라진 (장가르 습지대)",
    ["Zim'Torga, Zul'Drak"] = "짐토르가 (줄드락)",
    ["Zoram'gar Outpost, Ashenvale"] = "조람가르 전초기지 (잿빛 골짜기)",
    ["Zul'Aman, Ghostlands"] = "줄아만, 유령의 땅",
  },
  ["ruRU"] = {
    ["Acherus: The Ebon Hold"] = "Акерус: Черный оплот",
    ["Aerie Peak, The Hinterlands"] = "Заоблачный пик, Внутренние земли",
    ["Agmar's Hammer, Dragonblight"] = "Молот Агмара, Драконий Погост",
    ["Allerian Stronghold, Terokkar Forest"] = "Бастион Аллерии, лес Тероккар",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "Алтарь Ша'тар, Долина Призрачной Луны",
    ["Amber Ledge, Borean Tundra"] = "Янтарная гряда, Борейская тундра",
    ["Amberpine Lodge, Grizzly Hills"] = "Приют Янтарной Сосны, Седые холмы",
    ["Apothecary Camp, Howling Fjord"] = "Аптекарский поселок, Ревущий фьорд",
    ["Area 52, Netherstorm"] = "Зона 52, Пустоверть",
    ["Argent Stand, Zul'Drak"] = "Серебряная застава, Зул'Драк",
    ["Argent Tournament Grounds, Icecrown"] = "Ристалище Серебряного турнира, Ледяная Корона",
    ["Astranaar, Ashenvale"] = "Астранаар, Ясеневый лес",
    ["Auberdine, Darkshore"] = "Аубердин, Темные берега",
    ["Blood Watch, Bloodmyst Isle"] = "Кровавая застава, остров Кровавой Дымки",
    ["Bloodvenom Post, Felwood"] = "Застава Отравленной Крови, Оскверненный лес",
    ["Booty Bay, Stranglethorn"] = "Пиратская Бухта, Тернистая долина",
    ["Bor'gorok Outpost, Borean Tundra"] = "Застава Бор'горока, Борейская тундра",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "Приют Глыбоскала, Грозовая Гряда",
    ["Brackenwall Village, Dustwallow Marsh"] = "Деревня Гиблотопь, Пылевые топи",
    ["Camp Mojache, Feralas"] = "Лагерь Мохаче, Фералас",
    ["Camp Oneqwah, Grizzly Hills"] = "Лагерь Уанква, Седые холмы",
    ["Camp Taurajo, The Barrens"] = "Лагерь Таурахо, Степи",
    ["Camp Tunka'lo, The Storm Peaks"] = "Лагерь Тунка'ло, Грозовая Гряда",
    ["Camp Winterhoof, Howling Fjord"] = "Лагерь Заиндевевшего Копыта, Ревущий Фьорд",
    ["Cenarion Hold, Silithus"] = "Крепость Кенария, Силитус",
    ["Chillwind Camp, Western Plaguelands"] = "Лагерь Промозглого Ветра, Западные Чумные земли",
    ["Cosmowrench, Netherstorm"] = "Космоворот, Пустоверть",
    ["Crossroads, The Barrens"] = "Перекресток, Степи",
    ["Crown Guard Tower, Eastern Plaguelands"] = "Башня королевской стражи, Восточные Чумные земли",
    ["Crusaders' Pinnacle, Icecrown"] = "Вершина Рыцарей, Ледяная Корона",
    ["Dalaran"] = "Даларан",
    ["Darkshire, Duskwood"] = "Темнолесье, Сумеречный лес",
    ["Death's Rise, Icecrown"] = "Уступ Смерти, Ледяная Корона",
    ["Dun Nifflelem, The Storm Peaks"] = "Дун Ниффелем, Грозовая Гряда",
    ["Eastwall Tower, Eastern Plaguelands"] = "Восточная башня, Восточные Чумные земли",
    ["Ebon Watch, Zul'Drak"] = "Черная застава, Зул'Драк",
    ["Emerald Sanctuary, Felwood"] = "Изумрудное святилище, Оскверненный лес",
    ["Evergrove, Blade's Edge Mountains"] = "Вечная роща, Острогорье",
    ["Everlook, Winterspring"] = "Круговзор, Зимние Ключи",
    ["Falcon Watch, Hellfire Peninsula"] = "Соколиный Дозор, Полуостров Адского Пламени",
    ["Feathermoon, Feralas"] = "Крепость Оперенной Луны, Фералас",
    ["Fishing Village, Teldrassil"] = "Рыбацкий поселок, Тельдрассил",
    ["Fizzcrank Airstrip, Borean Tundra"] = "Взлетная полоса Выкрутеня, Борейская тундра",
    ["Flame Crest, Burning Steppes"] = "Пламенеющий Стяг, Пылающие степи",
    ["Fordragon Hold, Dragonblight"] = "Крепость Фордрагона, Драконий Погост",
    ["Forest Song, Ashenvale"] = "Лесная Песнь, Ясеневый лес",
    ["Fort Wildervar, Howling Fjord"] = "Крепость Вилдервар, Ревущий фьорд",
    ["Freewind Post, Thousand Needles"] = "Застава Вольный Ветер, Тысяча Игл",
    ["Frosthold, The Storm Peaks"] = "Ледяная крепость, Грозовая Гряда",
    ["Gadgetzan, Tanaris"] = "Прибамбасск, Танарис",
    ["Garadar, Nagrand"] = "Гарадар, Награнд",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "Место крушения Гром'арша, Грозовая Гряда",
    ["Grom'gol, Stranglethorn"] = "Гром'гол, Тернистая долина",
    ["Gundrak, Zul'Drak"] = "Гундрак, Зул'Драк",
    ["Hammerfall, Arathi"] = "Павший Молот, Арати",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "Полуостров Адского Пламени - Темный портал, Альянс",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "Полуостров Адского Пламени - Темный портал, Орда",
    ["Honor Hold, Hellfire Peninsula"] = "Оплот Чести, Полуостров Адского Пламени",
    ["Ironforge, Dun Morogh"] = "Стальгорн, Дун Морог",
    ["K3, The Storm Peaks"] = "К-3, Грозовая Гряда",
    ["Kamagua, Howling Fjord"] = "Камагуа, Ревущий фьорд",
    ["Kargath, Badlands"] = "Каргат, Бесплодные земли",
    ["Kor'koron Vanguard, Dragonblight"] = "Стоянка отряда Кор'крона, Драконий Погост",
    ["Lakeshire, Redridge"] = "Приозерье, Красногорье",
    ["Light's Breach, Zul'Drak"] = "Разлом Света, Зул'Драк",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "Часовня Последней Надежды, Восточные Чумные земли",
    ["Marshal's Refuge, Un'Goro Crater"] = "Укрытие Маршалла, Кратер Ун'Горо",
    ["Menethil Harbor, Wetlands"] = "Гавань Менетилов, Болотина",
    ["Moa'ki, Dragonblight"] = "Моа'ки, Драконий Погост",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "Деревня Мок'Натал, Острогорье",
    ["Moonglade"] = "Лунная поляна",
    ["Morgan's Vigil, Burning Steppes"] = "Дозор Моргана, Пылающие степи",
    ["Mudsprocket, Dustwallow Marsh"] = "Шестермуть, Пылевые топи",
    ["Nesingwary Base Camp, Sholazar Basin"] = "Лагерь Эрнестуэя, Низина Шолазар",
    ["Nethergarde Keep, Blasted Lands"] = "Крепость Стражей Пустоты, Выжженные земли",
    ["New Agamand, Howling Fjord"] = "Новый Агамонд, Ревущий Фьорд",
    ["Nighthaven, Moonglade"] = "Ночная Гавань, Лунная поляна",
    ["Nijel's Point, Desolace"] = "Высота Найджела, Пустоши",
    ["Northpass Tower, Eastern Plaguelands"] = "Башня Северного перевалa, Восточные Чумные земли",
    ["Ogri'La"] = "Огри'ла",
    ["Orebor Harborage, Zangarmarsh"] = "Прибежище Оребор, Зангартопь",
    ["Orgrimmar, Durotar"] = "Оргриммар, Дуротар",
    ["Plaguewood Tower, Eastern Plaguelands"] = "Башня Проклятого леса, Восточные Чумные земли",
    ["Ratchet, The Barrens"] = "Кабестан, Степи",
    ["Rebel Camp, Stranglethorn Vale"] = "Лагерь повстанцев, Тернистая долина",
    ["Refuge Pointe, Arathi"] = "Опорный пункт, Арати",
    ["Revantusk Village, The Hinterlands"] = "Деревня Сломанного Клыка, Внутренние земли",
    ["River's Heart, Sholazar Basin"] = "Слияние рек, Низина Шолазар",
    ["Rut'theran Village, Teldrassil"] = "Деревня Рут'теран, Тельдрассил",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "Святилище Звезд, Долина Призрачной Луны",
    ["Sentinel Hill, Westfall"] = "Сторожевой холм, Западный Край",
    ["Shadowmoon Village, Shadowmoon Valley"] = "Деревня Призрачной Луны, Долина Призрачной Луны",
    ["Shadowprey Village, Desolace"] = "Деревня Ночных Охотников, Пустоши",
    ["Shatter Point, Hellfire Peninsula"] = "Парящая застава, Полуостров Адского Пламени",
    ["Shattered Sun Staging Area"] = "Подготовительный плацдарм Расколотого Солнца",
    ["Shattrath, Terokkar Forest"] = "Шаттрат, лес Тероккар",
    ["Silvermoon City"] = "Луносвет",
    ["Skettis"] = "Скеттис",
    ["Southshore, Hillsbrad"] = "Южнобережье, Хилсбрад",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "Гребень Хребтолома, Полуостров Адского Пламени",
    ["Splintertree Post, Ashenvale"] = "Застава Расщепленного Дерева, Ясеневый лес",
    ["Stars' Rest, Dragonblight"] = "Покой Звезд, Драконий Погост",
    ["Stonard, Swamp of Sorrows"] = "Каменор, Болото Печали",
    ["Stonebreaker Hold, Terokkar Forest"] = "Форт Камнеломов, лес Тероккар",
    ["Stonetalon Peak, Stonetalon Mountains"] = "Пик Каменного Когтя, Когтистые горы",
    ["Stormwind, Elwynn"] = "Штормград, Элвин",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "Приют у Солнечного Камня, Когтистые горы",
    ["Sunreaver's Command, Crystalsong Forest"] = "Лагерь Похитителя Солнца, Ледяные Оковы",
    ["Swamprat Post, Zangarmarsh"] = "Застава Болотной Крысы, Зангартопь",
    ["Sylvanaar, Blade's Edge Mountains"] = "Сильванаар, Острогорье",
    ["Talonbranch Glade, Felwood"] = "Поляна Когтистых Ветвей, Оскверненный лес",
    ["Talrendis Point, Azshara"] = "Застава Талрендис, Азшара",
    ["Tarren Mill, Hillsbrad"] = "Мельница Таррен, Хилсбрад",
    ["Taunka'le Village, Borean Tundra"] = "Деревня Таунка'ле, Борейская тундра",
    ["Telaar, Nagrand"] = "Телаар, Награнд",
    ["Telredor, Zangarmarsh"] = "Телредор, Зангартопь",
    ["Temple of Telhamat, Hellfire Peninsula"] = "Храм Телхамата, Полуостров Адского Пламени",
    ["Thalanaar, Feralas"] = "Таланаар, Фералас",
    ["The Argent Vanguard, Icecrown"] = "Оплот Серебряного Авангарда, Ледяная Корона",
    ["The Bulwark, Tirisfal"] = "Бастион, Тирисфаль",
    ["The Exodar"] = "Экзодар",
    ["The Sepulcher, Silverpine Forest"] = "Гробница, Серебряный бор",
    ["The Shadow Vault, Icecrown"] = "Мрачный Свод, Ледяная Корона",
    ["The Stormspire, Netherstorm"] = "Штормовая Вершина, Пустоверть",
    ["Thelsamar, Loch Modan"] = "Телcамар, озеро Лок Модан",
    ["Theramore, Dustwallow Marsh"] = "Терамор, Пылевые топи",
    ["Thondoril River, Western Plaguelands"] = "Река Тондрорил, Западные Чумные земли",
    ["Thorium Point, Searing Gorge"] = "Лагерь Братства Тория, Тлеющее ущелье",
    ["Thrallmar, Hellfire Peninsula"] = "Траллмар, Полуостров Адского Пламени",
    ["Thunder Bluff, Mulgore"] = "Громовой Утес, Мулгор",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "Оплот Громоборцев, Острогорье",
    ["Toshley's Station, Blade's Edge Mountains"] = "Станция Тошли, Острогорье",
    ["Tranquillien, Ghostlands"] = "Транквиллион, Призрачные земли",
    ["Transitus Shield, Coldarra"] = "Маскировочный щит, Хладарра",
    ["Ulduar, The Storm Peaks"] = "Ульдуар, Грозовая Гряда",
    ["Undercity, Tirisfal"] = "Подгород, Тирисфаль",
    ["Unu'pe, Borean Tundra"] = "Уну'пе, Борейская тундра",
    ["Valgarde Port, Howling Fjord"] = "Валгардский порт, Ревущий фьорд",
    ["Valiance Keep, Borean Tundra"] = "Крепость Отваги, Борейская тундра",
    ["Valiance Landing Camp, Wintergrasp"] = "Лагерь Отваги, Ледяные Оковы",
    ["Valormok, Azshara"] = "Храбростан, Азшара",
    ["Vengeance Landing, Howling Fjord"] = "Лагерь Возмездия, Ревущий Фьорд",
    ["Venomspite, Dragonblight"] = "Ядозлобь, Драконий Погост",
    ["Warsong Camp, Wintergrasp"] = "Лагерь Песни Войны, Ледяные Оковы",
    ["Warsong Hold, Borean Tundra"] = "Крепость Песни Войны, Борейская тундра",
    ["Westfall Brigade, Grizzly Hills"] = "Лагерь дружины Западного Края, Седые холмы",
    ["Westguard Keep, Howling Fjord"] = "Крепость Западной Стражи, Ревущий фьорд",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "Цитадель Громового Молота, Долина Призрачной Луны",
    ["Windrunner's Overlook, Crystalsong Forest"] = "Дозор Ветрокрылой, Лес Хрустальной Песни",
    ["Wintergarde Keep, Dragonblight"] = "Крепость Стражей Зимы, Драконий Погост",
    ["Wyrmrest Temple, Dragonblight"] = "Храм Драконьего Покоя, Драконий Погост",
    ["Zabra'jin, Zangarmarsh"] = "Забра'джин, Зангартопь",
    ["Zim'Torga, Zul'Drak"] = "Зим'Торга, Зул'Драк",
    ["Zoram'gar Outpost, Ashenvale"] = "Форт Зорам'гар, Ясеневый лес",
    ["Zul'Aman, Ghostlands"] = "Зул'Аман, Призрачные земли",
  },
  ["zhCN"] = {
    ["Acherus: The Ebon Hold"] = "阿彻鲁斯：黑锋要塞",
    ["Aerie Peak, The Hinterlands"] = "鹰巢山，辛特兰",
    ["Agmar's Hammer, Dragonblight"] = "阿格玛之锤，龙骨荒野",
    ["Allerian Stronghold, Terokkar Forest"] = "奥蕾莉亚要塞，泰罗卡森林",
    ["Altar of Sha'tar, Shadowmoon Valley"] = "沙塔尔祭坛，影月谷",
    ["Amber Ledge, Borean Tundra"] = "琥珀崖，北风苔原",
    ["Amberpine Lodge, Grizzly Hills"] = "琥珀松木营地，灰熊丘陵",
    ["Apothecary Camp, Howling Fjord"] = "药剂师营地，嚎风峡湾",
    ["Area 52, Netherstorm"] = "52区，虚空风暴",
    ["Argent Stand, Zul'Drak"] = "银色前沿，祖达克",
    ["Argent Tournament Grounds, Icecrown"] = "银色比武场，冰冠冰川",
    ["Astranaar, Ashenvale"] = "阿斯特兰纳，灰谷",
    ["Auberdine, Darkshore"] = "奥伯丁，黑海岸",
    ["Blood Watch, Bloodmyst Isle"] = "秘血岗哨，秘血岛",
    ["Bloodvenom Post, Felwood"] = "血毒河，费伍德森林",
    ["Booty Bay, Stranglethorn"] = "藏宝海湾，荆棘谷",
    ["Bor'gorok Outpost, Borean Tundra"] = "博古洛克前哨站，北风苔原",
    ["Bouldercrag's Refuge, The Storm Peaks"] = "布德克拉格庇护所，风暴峭壁",
    ["Brackenwall Village, Dustwallow Marsh"] = "蕨墙村，尘泥沼泽",
    ["Camp Mojache, Feralas"] = "莫沙彻营地，菲拉斯",
    ["Camp Oneqwah, Grizzly Hills"] = "欧尼瓦营地，灰熊丘陵",
    ["Camp Taurajo, The Barrens"] = "陶拉祖营地，贫瘠之地",
    ["Camp Tunka'lo, The Storm Peaks"] = "唐卡洛营地，风暴峭壁",
    ["Camp Winterhoof, Howling Fjord"] = "冬蹄营地，嚎风峡湾",
    ["Cenarion Hold, Silithus"] = "塞纳里奥要塞，希利苏斯",
    ["Chillwind Camp, Western Plaguelands"] = "冰风岗，西瘟疫之地",
    ["Cosmowrench, Netherstorm"] = "扳钳镇，虚空风暴",
    ["Crossroads, The Barrens"] = "十字路口，贫瘠之地",
    ["Crown Guard Tower, Eastern Plaguelands"] = "皇冠哨塔，东瘟疫之地",
    ["Crusaders' Pinnacle, Icecrown"] = "北伐军之峰，冰冠冰川",
    ["Dalaran"] = "达拉然",
    ["Darkshire, Duskwood"] = "夜色镇，暮色森林",
    ["Death's Rise, Icecrown"] = "死亡高地，冰冠冰川",
    ["Dun Nifflelem, The Storm Peaks"] = "丹尼芬雷，风暴峭壁",
    ["Eastwall Tower, Eastern Plaguelands"] = "东墙哨塔，东瘟疫之地",
    ["Ebon Watch, Zul'Drak"] = "黑锋哨站，祖达克",
    ["Emerald Sanctuary, Felwood"] = "翡翠圣地，费伍德森林",
    ["Evergrove, Blade's Edge Mountains"] = "常青林，刀锋山",
    ["Everlook, Winterspring"] = "永望镇，冬泉谷",
    ["Falcon Watch, Hellfire Peninsula"] = "猎鹰岗哨，地狱火半岛",
    ["Feathermoon, Feralas"] = "羽月要塞，菲拉斯",
    ["Fishing Village, Teldrassil"] = "钓鱼村，泰达希尔",
    ["Fizzcrank Airstrip, Borean Tundra"] = "菲兹兰克机场，北风苔原",
    ["Flame Crest, Burning Steppes"] = "烈焰峰，燃烧平原",
    ["Fordragon Hold, Dragonblight"] = "弗塔根要塞，龙骨荒野",
    ["Forest Song, Ashenvale"] = "林歌神殿，灰谷",
    ["Fort Wildervar, Howling Fjord"] = "维德瓦堡垒，嚎风峡湾",
    ["Freewind Post, Thousand Needles"] = "乱风岗 ，千针石林",
    ["Frosthold, The Storm Peaks"] = "冰霜堡，风暴峭壁",
    ["Gadgetzan, Tanaris"] = "加基森，塔纳利斯",
    ["Garadar, Nagrand"] = "加拉达尔，纳格兰",
    ["Grom'arsh Crash-Site, The Storm Peaks"] = "格罗玛什坠毁点，风暴峭壁",
    ["Grom'gol, Stranglethorn"] = "格罗姆高，荆棘谷",
    ["Gundrak, Zul'Drak"] = "古达克，祖达克",
    ["Hammerfall, Arathi"] = "落锤镇，阿拉希高地",
    ["Hellfire Peninsula, The Dark Portal, Alliance"] = "地狱火半岛，黑暗之门，联盟",
    ["Hellfire Peninsula, The Dark Portal, Horde"] = "地狱火半岛，黑暗之门，部落",
    ["Honor Hold, Hellfire Peninsula"] = "荣耀堡，地狱火半岛",
    ["Ironforge, Dun Morogh"] = "铁炉堡，丹莫罗",
    ["K3, The Storm Peaks"] = "K3，风暴峭壁",
    ["Kamagua, Howling Fjord"] = "卡玛古，嚎风峡湾",
    ["Kargath, Badlands"] = "卡加斯，荒芜之地",
    ["Kor'koron Vanguard, Dragonblight"] = "库卡隆先锋营地，龙骨荒野",
    ["Lakeshire, Redridge"] = "湖畔镇，赤脊山",
    ["Light's Breach, Zul'Drak"] = "圣光据点，祖达克",
    ["Light's Hope Chapel, Eastern Plaguelands"] = "圣光之愿礼拜堂，东瘟疫之地",
    ["Marshal's Refuge, Un'Goro Crater"] = "马绍尔营地，安戈洛环形山",
    ["Menethil Harbor, Wetlands"] = "米奈希尔港，湿地",
    ["Moa'ki, Dragonblight"] = "莫亚基，龙骨荒野",
    ["Mok'Nathal Village, Blade's Edge Mountains"] = "莫克纳萨村，刀锋山",
    ["Moonglade"] = "月光林地",
    ["Morgan's Vigil, Burning Steppes"] = "摩根的岗哨，燃烧平原",
    ["Mudsprocket, Dustwallow Marsh"] = "泥链镇，尘泥沼泽",
    ["Nesingwary Base Camp, Sholazar Basin"] = "奈辛瓦里营地，索拉查盆地",
    ["Nethergarde Keep, Blasted Lands"] = "守望堡，诅咒之地",
    ["New Agamand, Howling Fjord"] = "新阿加曼德，嚎风峡湾",
    ["Nighthaven, Moonglade"] = "永夜港，月光林地",
    ["Nijel's Point, Desolace"] = "尼耶尔前哨站，凄凉之地",
    ["Northpass Tower, Eastern Plaguelands"] = "北地哨塔，东瘟疫之地",
    ["Ogri'La"] = "奥格瑞拉",
    ["Orebor Harborage, Zangarmarsh"] = "奥雷柏尔营地，赞加沼泽",
    ["Orgrimmar, Durotar"] = "奥格瑞玛，杜隆塔尔",
    ["Plaguewood Tower, Eastern Plaguelands"] = "病木林哨塔，东瘟疫之地",
    ["Ratchet, The Barrens"] = "棘齿城，贫瘠之地",
    ["Rebel Camp, Stranglethorn Vale"] = "反抗军营地，荆棘谷",
    ["Refuge Pointe, Arathi"] = "避难谷地，阿拉希高地",
    ["Revantusk Village, The Hinterlands"] = "恶齿村，辛特兰",
    ["River's Heart, Sholazar Basin"] = "河流之心，索拉查盆地",
    ["Rut'theran Village, Teldrassil"] = "鲁瑟兰村，泰达希尔",
    ["Sanctum of the Stars, Shadowmoon Valley"] = "群星圣殿，影月谷",
    ["Sentinel Hill, Westfall"] = "哨兵岭，西部荒野",
    ["Shadowmoon Village, Shadowmoon Valley"] = "影月村，影月谷",
    ["Shadowprey Village, Desolace"] = "葬影村，凄凉之地",
    ["Shatter Point, Hellfire Peninsula"] = "破碎岗哨，地狱火半岛",
    ["Shattered Sun Staging Area"] = "破碎残阳基地",
    ["Shattrath, Terokkar Forest"] = "沙塔斯，泰罗卡森林",
    ["Silvermoon City"] = "银月城",
    ["Skettis"] = "斯克提斯",
    ["Southshore, Hillsbrad"] = "南海镇，希尔斯布莱德",
    ["Spinebreaker Ridge, Hellfire Peninsula"] = "断背山，地狱火半岛",
    ["Splintertree Post, Ashenvale"] = "碎木岗哨，灰谷",
    ["Stars' Rest, Dragonblight"] = "群星之墓，龙骨荒野",
    ["Stonard, Swamp of Sorrows"] = "斯通纳德，悲伤沼泽",
    ["Stonebreaker Hold, Terokkar Forest"] = "裂石堡，泰罗卡森林",
    ["Stonetalon Peak, Stonetalon Mountains"] = "石爪峰，石爪山",
    ["Stormwind, Elwynn"] = "暴风城，艾尔文森林",
    ["Sun Rock Retreat, Stonetalon Mountains"] = "烈日石居，石爪山",
    ["Sunreaver's Command, Crystalsong Forest"] = "夺日者指挥站，晶歌森林",
    ["Swamprat Post, Zangarmarsh"] = "沼泽鼠岗哨，赞加沼泽",
    ["Sylvanaar, Blade's Edge Mountains"] = "希尔瓦纳，刀锋山",
    ["Talonbranch Glade, Felwood"] = "刺枝林地，费伍德森林",
    ["Talrendis Point, Azshara"] = "塔伦迪斯营地，艾萨拉",
    ["Tarren Mill, Hillsbrad"] = "塔伦米尔，希尔斯布莱德",
    ["Taunka'le Village, Borean Tundra"] = "牦牛村，北风苔原",
    ["Telaar, Nagrand"] = "塔拉，纳格兰",
    ["Telredor, Zangarmarsh"] = "泰雷多尔，赞加沼泽",
    ["Temple of Telhamat, Hellfire Peninsula"] = "塔哈玛特神殿，地狱火半岛",
    ["Thalanaar, Feralas"] = "萨兰纳尔，千针石林",
    ["The Argent Vanguard, Icecrown"] = "银色前线基地，冰冠冰川",
    ["The Bulwark, Tirisfal"] = "亡灵壁垒，提瑞斯法",
    ["The Exodar"] = "埃索达",
    ["The Sepulcher, Silverpine Forest"] = "瑟伯切尔，银松森林",
    ["The Shadow Vault, Icecrown"] = "暗影拱顶，冰冠冰川",
    ["The Stormspire, Netherstorm"] = "风暴尖塔，虚空风暴",
    ["Thelsamar, Loch Modan"] = "塞尔萨玛，洛克莫丹",
    ["Theramore, Dustwallow Marsh"] = "塞拉摩，尘泥沼泽",
    ["Thondoril River, Western Plaguelands"] = "索多里尔河，西瘟疫之地",
    ["Thorium Point, Searing Gorge"] = "瑟银哨塔，灼热峡谷",
    ["Thrallmar, Hellfire Peninsula"] = "萨尔玛，地狱火半岛",
    ["Thunder Bluff, Mulgore"] = "雷霆崖，莫高雷",
    ["Thunderlord Stronghold, Blade's Edge Mountains"] = "雷神要塞，刀锋山",
    ["Toshley's Station, Blade's Edge Mountains"] = "托什雷的基地，刀锋山",
    ["Tranquillien, Ghostlands"] = "塔奎林，幽魂之地",
    ["Transitus Shield, Coldarra"] = "永生之盾，考达拉",
    ["Ulduar, The Storm Peaks"] = "奥杜尔，风暴峭壁",
    ["Undercity, Tirisfal"] = "幽暗城，提瑞斯法林地",
    ["Unu'pe, Borean Tundra"] = "乌努比，北风苔原",
    ["Valgarde Port, Howling Fjord"] = "瓦加德港口，嚎风峡湾",
    ["Valiance Keep, Borean Tundra"] = "无畏要塞，北风苔原",
    ["Valiance Landing Camp, Wintergrasp"] = "无畏远征军营地，冬拥湖",
    ["Valormok, Azshara"] = "瓦罗莫克，艾萨拉",
    ["Vengeance Landing, Howling Fjord"] = "复仇港，嚎风峡湾",
    ["Venomspite, Dragonblight"] = "怨毒镇，龙骨荒野",
    ["Warsong Camp, Wintergrasp"] = "战歌营地，冬拥湖",
    ["Warsong Hold, Borean Tundra"] = "战歌要塞，北风苔原",
    ["Westfall Brigade, Grizzly Hills"] = "月溪旅，灰熊丘陵",
    ["Westguard Keep, Howling Fjord"] = "西部卫戍要塞，嚎风峡湾",
    ["Wildhammer Stronghold, Shadowmoon Valley"] = "蛮锤要塞，影月谷",
    ["Windrunner's Overlook, Crystalsong Forest"] = "风行者观察站，晶歌森林",
    ["Wintergarde Keep, Dragonblight"] = "暮冬要塞，龙骨荒野",
    ["Wyrmrest Temple, Dragonblight"] = "龙眠神殿，龙骨荒野",
    ["Zabra'jin, Zangarmarsh"] = "萨布拉金，赞加沼泽",
    ["Zim'Torga, Zul'Drak"] = "希姆托加，祖达克",
    ["Zoram'gar Outpost, Ashenvale"] = "佐拉姆加前哨站，灰谷",
    ["Zul'Aman, Ghostlands"] = "祖阿曼，幽魂之地",
  },
}
